### ISSUE TITLE
Cometvisu does NOT work with any current KNXD 

### ISSUE THREAD

**Issue by lassos** [knxd/knxd#493] opened 2020-12-05 14:54 UTC
same here. latest cometvisu with knxd and debian buster not working.

https://knx-user-forum.de/forum/supportforen/cometvisu/1560015-knxd-cometvisu-caching-ladezeiten

"...Beim knxd wurden vor einiger Zeit ohne Rücksprache und Absicherungen Änderungen eingeführt, die mit der CometVisu nicht kompatibel waren. Ob die zwischenzeitlich gefixt wurden weiß ich leider nicht.

Praktisch bin ich - und damit auch die offiziellen CometVisu Docker Container - daher auf der wunderbar stabil funktionierenden Version 0.0.5.1 geblieben.

Ich schätze, dass ein Fix für den aktuellen knxd nicht sonderlich schwer ist. Aber es hat sich bisher halt noch niemand dafür interessiert...

**Comment by ChristianMayer** [comment] 2020-12-13 22:44
Running the "r" request from the CometVisu demo config it takes very long for the initial read to answer. This can be also seen from the command line without the web server by running:
```
export REQUEST_METHOD=GET QUERY_STRING='t=0&s=SESSION&a=12/7/9&a=12/7/1&a=12/7/2&a=12/7/20&a=12/7/5&a=12/7/105&a=12/7/16&a=12/7/10&a=12/7/100&a=12/7/90&a=12/7/91&a=12/7/92&a=12/7/93&a=12/7/50&a=12/7/51&a=12/7/52'  && time /usr/lib/cgi-bin/r
Content-Type: text/plain

{"d": {"12/7/1":"00","12/7/2":"00","12/7/20":"02","12/7/50":"1A","12/7/90":"152E"},"i":0}

real    0m11.028s
user    0m0.008s
sys     0m0.004s
```
Note: `/usr/lib/cgi-bin/r` is `eibread-cgi`. The knxd version is `knxd 0.14.39-4-g9929ed6`

To understand the test case a bit better:
The knxd is connected to my knx (via the Timberwolf) and running for quite a while, so the cache should be filled. None of the GAs do exists (as being mapped to an object of an knx device) on my bus, i.e. all read requests to them will never be answered. But some of the values were already being sent to in the past (by playing with the visu demo) and thus their value is in the knxd cache. This can be seen from the answer (`{"d": {"12/7/1":" ...`).

Running a bus monitor (connected to the same knxd) in parallel I can see (with roughly 1 second between each of these lines):
```
22:26:13.639 L_Busmon: BC 11 AA 67 05 E1 00 00 7B :L_Data low from 1.1.170 to 12/7/5 hops: 06 T_Data_Group A_GroupValue_Read
22:26:14.640 L_Busmon: BC 11 AA 67 09 E1 00 00 77 :L_Data low from 1.1.170 to 12/7/9 hops: 06 T_Data_Group A_GroupValue_Read
22:26:15.642 L_Busmon: BC 11 AA 67 0A E1 00 00 74 :L_Data low from 1.1.170 to 12/7/10 hops: 06 T_Data_Group A_GroupValue_Read
22:26:16.643 L_Busmon: BC 11 AA 67 10 E1 00 00 6E :L_Data low from 1.1.170 to 12/7/16 hops: 06 T_Data_Group A_GroupValue_Read
22:26:17.646 L_Busmon: BC 11 AA 67 33 E1 00 00 4D :L_Data low from 1.1.170 to 12/7/51 hops: 06 T_Data_Group A_GroupValue_Read
22:26:18.647 L_Busmon: BC 11 AA 67 34 E1 00 00 4A :L_Data low from 1.1.170 to 12/7/52 hops: 06 T_Data_Group A_GroupValue_Read
22:26:19.649 L_Busmon: BC 11 AA 67 5B E1 00 00 25 :L_Data low from 1.1.170 to 12/7/91 hops: 06 T_Data_Group A_GroupValue_Read
22:26:20.650 L_Busmon: BC 11 AA 67 5C E1 00 00 22 :L_Data low from 1.1.170 to 12/7/92 hops: 06 T_Data_Group A_GroupValue_Read
22:26:21.652 L_Busmon: BC 11 AA 67 5D E1 00 00 23 :L_Data low from 1.1.170 to 12/7/93 hops: 06 T_Data_Group A_GroupValue_Read
22:26:22.653 L_Busmon: BC 11 AA 67 64 E1 00 00 1A :L_Data low from 1.1.170 to 12/7/100 hops: 06 T_Data_Group A_GroupValue_Read
22:26:23.654 L_Busmon: BC 11 AA 67 69 E1 00 00 17 :L_Data low from 1.1.170 to 12/7/105 hops: 06 T_Data_Group A_GroupValue_Read
```
Expected result:
----

As defined in the protocol (https://github.com/CometVisu/CometVisu/wiki/Protocol#read) the usage of `t=0` defines that it should be answered out of the cache. So the answer should come immediately. And the read requests should be sent in parallel, any delay between them is not necessary (except, perhaps, as a rate limiter)

**Comment by smurfix** [comment] 2020-12-14 08:07
> As defined in the protocol (https://github.com/CometVisu/CometVisu/wiki/Protocol#read) the usage of t=0 defines that it should be answered out of the cache.

Umm, well, the spec says

> Is TIMEOUT equal to "0" or if there is no relevant data in the cache the backend will try to read the data from the bus. A negative TIMEOUT will only deliver data out of the cache, reading from the bus will not happen. 

so frankly I don't think t=0 should answer immediately. If you want that, use t=-1. I think.

That being said I agree that waiting a full second between requests is nonsense. I'll also look into the rest.

**Comment by ChristianMayer** [comment] 2020-12-14 08:38
You are right that the spec could be a bit clearer here.

So far the implementation was (and the CometVisu was working very well with that) that `t=0` means: answer everything possible from the cache immediately and ask the bus for the rest.
All other values for t are defined but not used in reality, as far as I know.

BTW: I've checked t=-1 as well - but it's behaving like t=0.

**Comment by smurfix** [comment] 2020-12-14 12:21
The problem is that "ask the bus" doesn't work in parallel. It never did. Doing that is a good idea in principle but I'm sufficiently unhappy with the state of knxd's internal API, as well as the CGI code, to not attempt that in its current incarnation.

**Comment by ChristianMayer** [comment] 2020-12-14 13:20
It doesn't need to be technically parallel. Within a short time frame is completely sufficient. 

Assuming a simple single cored system it would work like:
User starts up CometVisu -> first "r" call (i.e. with `t=0` and a few GAs of interest to the user) -> Web-Server -> eibread-cgi -> knxd

Then at the knxd side it happens in this sequence:
- knxd answers all GA values (the latest value) it knows from the cache immediately and sends them back together with the `i` of the current cache index
- knxd sends just afterwards the read requests for all GAs that weren't in the cache  

Done

The client displays all values from the answer and immediately opens a new `r` call, but this time with `i=<the just recived number>` (instead of the `t=0`).
Then on knxd side the following is happening:
- when it has recieved any of the requested GAs in the meantime (i.e. since the cache index was at the `i` value) those values will be returned immediately together with a new `i`
- when it has not recived any of the requested GAs in the meantime it is holding the answer open till any one of those GAs is apparing on the bus. Then it is returned immediately together with a new `i`

For the CGI code I'd also prefer a C++ implementation as it's still possible to be light weight but also far saver with regard to possible bugs that might end up as being security threads. (Just switching to C++ strings would most likely be the 80:20 solution)
On the other hand we do have a well working and widely used solution since 10 years now. So I'm not too eager to change things here.

**Comment by smurfix** [comment] 2020-12-14 17:23
I have committed some minor changes. Seems to work very well for larsknx (@ knx-user-forum.de) who wrote that it's as responsive as the old eibd now. Checked in at the `test` branch. Main change is to reduce the cache read timeout to 75 msec. Please test.

Changes like assigning fixed phys addresses to CGI programs will have to wait, at the very least that requires a protocol extension.

**Comment by ChristianMayer** [comment] 2020-12-15 14:05
The test branch is much better now!

But it still has drawbacks:
```
export REQUEST_METHOD=GET QUERY_STRING='t=0&s=SESSION&a=12/7/9&a=12/7/1&a=12/7/2&a=12/7/20&a=12/7/5&a=12/7/105&a=12/7/16&a=12/7/10&a=12/7/100&a=12/7/90&a=12/7/91&a=12/7/92&a=12/7/93&a=12/7/50&a=12/7/51&a=12/7/52'  && time /usr/lib/cgi-bin/r
Content-Type: text/plain

{"d": {"12/7/1":"01","12/7/2":"01","12/7/90":"152E"},"i":0}

real    0m0.991s
user    0m0.004s
sys     0m0.004s
```
=> Answer is still taking 1 seconds (sometimes longer, in this test run just below 1 sec), this could/should be much quicker - I'd guess less than 100 ms could be expected
(When the 1 second is constant and doesn't scale with the number of GAs requested the situation might be acceptable; when it's not fix it might cause an issue, already in normal installations)

=> The answer has an `"i":0` which isn't correct

All following requests (i.e. with `i=` instead of the `t=0`) were looking fine. Also the response time was fine (< 10 ms).

**Comment by smurfix** [comment] 2020-12-15 15:16
`i=0` is not avoidable without protocol changes. However it isn't a problem except for a couple of duplicate replies which KNX requires you to tolerate anyway.

I don't (yet) know why your test takes almost a second, in principle this should pass in <250msec with the current code and a "cold" cache. Are those GAs in the cache?  If not, do the read requests actually get answered – what's happening on the bus and what's the timing?

**Comment by ChristianMayer** [comment] 2020-12-15 16:03
Double replies are not a big problem. They might get displayed at the visu twice, i.e. they might create a little "flicker" that is visible to the user. 

My test had 3 the 3 GAs visible in the reply in the cache as well as many unrelated GAs. The 13 other GAs of my request were not in the cache and their read request will never be answered as no device on the bus is responsible for them.
For a `t=0` the answer speed of the bus shouldn't matter anyway as it should answer the request before any A_GroupValue_Response will arrive. Those values will be transfered by one of the following `r` requests (that's why the `i` is important as it makes sure that no data will be forgotten)

**Comment by smurfix** [comment] 2020-12-15 16:43
The problem is that I can't just fire off a heap of responses back-to-back, if nothing else some bus capacity must be left for replies to come in. Also the memory of those small gateways is constrained and if you use multicast there's no flow control.

I also can't tell knxd to remember that these requests should be sent soon(ish). The old knxd protocol has no method to tell knxd to do that. I'll have to think about how to implement this in a reasonable way.

> My test had 3 the 3 GAs visible in the reply in the cache as well as many unrelated GAs.

Ah, right, I didn't look at that request closely enough. Sorry.

> The 13 other GAs of my request were not in the cache and their read request will never be answered as no device on the bus is responsible for them.

Well, frankly that's part of your problem: your visualization doesn't know the difference between GAs that can be actively read and those that are passive, it just fires off read requests indiscriminately. That's not how KNX is supposed to be used; in fact I consider this to be a bug in the visu. Worse, those blind read requests are not ACKed, thus the bus transceiver repeats them two or three times. This further slows down the bus when it starts up.

… and yes I know about the `i` parameter, one of the first changes I made to knxd's internal protocol was to extend its value to 32 bits, instead of letting it wrap around …

**Comment by ChristianMayer** [comment] 2020-12-15 17:49
> I also can't tell knxd to remember that these requests should be sent soon(ish). The old knxd protocol has no method to tell knxd to do that. I'll have to think about how to implement this in a reasonable way.

A FIFO buffer comes to my mind that stores everything that should be sent and sends them as soon as a rate limiter is allowing it to

> > The 13 other GAs of my request were not in the cache and their read request will never be answered as no device on the bus is responsible for them.
> 
> Well, frankly that's part of your problem: your visualization doesn't know the difference between GAs that can be actively read and those that are passive, it just fires off read requests indiscriminately. That's not how KNX is supposed to be used; in fact I consider this to be a bug in the visu. Worse, those blind read requests are not ACKed, thus the bus transceiver repeats them two or three times. This further slows down the bus when it starts up.

The visu is actually only asking for read requests during its start up (or when the chain of `r` requests was broken, e.g. due to a time out that could happen when no interesting bus traffic is happening). That's with the `t=0`. After that inital request it's only asking for the values that have arrived since the last communication has happend, the `i=<last answer>`.
I cannot see how the visu is thus "fireing off read requests", only the initial "please give me the values for everything the user wants to see right now"

When the configuration of the visu is demanding to show values of a GA that doesn't exist it's the fault of the creator of the configuration. It's not the fault of the visu, it's just doing it's job.
(What I'm doing here with the tests is just testing, it's not representative of the majority of real use. But these testcases do happen in reality, so they must be tested and work fine)

> … and yes I know about the `i` parameter, one of the first changes I made to knxd's internal protocol was to extend its value to 32 bits, instead of letting it wrap around …

Was there a problem with the wrap?
It actually only needed to cover the amount of bus packets that could arrive between the last answer of the eibread-cgi and the next call to it. So with a slow client and a slow network perhaps a time frame of 100 ms - which would mean by 150 packets/second (that most KNX devices couldn't handle anyway) an amount of 15 values, which would even fit into a 8 bit value.
But to be able to use any implementation on the backend (e.g. it also could be hash instead of a number) the type of value for `i` was on purpose not specified, so 32 bit are also fine.

**Comment by smurfix** [comment] 2020-12-15 18:37
> When the configuration of the visu is demanding to show values of a GA that doesn't exist it's the fault of the creator of the configuration. It's not the fault of the visu, it's just doing it's job.

"its job".
The problem is that the job is under-specified on the visu side. The ETS has a specific flag whether a GA can be read or not. Bus participants are supposed to adhere to that.

Everything would be (mostly) fine if the visu simply would not ask for the unreadable GAs when t=0.

**Comment by ChristianMayer** [comment] 2020-12-15 19:04
Please tell that all the persons who are creating the visu configs.

There's no sensible technical way for the visu software to enforce that as this information isn't available.
BTW: Even the ETS allows you to read a GA that has no device with that flag (you can even read GAs that have no device associated at all...) - although it has all the relevant information.

**Comment by smurfix** [comment] 2020-12-16 16:52
It's all software. It's certainly possible to add a way to *make* that information available. Simply try to read the address (without using the cache of course) and remember whether you got a reply. You can do this today via knxtool, or sometime soon (once I write the code …) using the websocket.

(Part of) my point here is that a bus or visu restart is the absolutely worst time to send a heap of unnecessary, duplicated, and unanswered packets onto the KNX bus. Best case the bus is slowed down somewhat, worst case vital information gets lost when the gateway is flooded with too many packets -- multicast doesn't have flow control.

**Closed** 2021-04-27 07:34 UTC
