### ISSUE TITLE
Migration to 0.11 failed: knxd does not connect to standard port 3671 any more

### ISSUE THREAD

**Issue by mclane** [knxd/knxd#156] opened 2016-10-10 21:12 UTC
I have tried to update from knxd 0.10.0 to 0.11 (new git master):
- cloned sources into a new directory, compiled them
- removed the old knxd installation via dpkg -p ...
- reinstalled new files

The old installation worked (more or less) fine; I could program from ETS5; group monitor worked, bus monitor created frame errors.

The new installation shows arbitrary IP ports in ETS5 (every time I start the knxd a different one); typically in the high area (>30 000) and I cannot establish a reliable connection. The port even changes if I try to connect from ETS5

My setup: 
- Raspi 3 with Debian Jessie
- /dev/ttyAMA0 re-established as described in various posts
- Siemens 5WG1117 connected to the serial port (via opto couplers)

My knxd.conf:
KNXD_OPTS="-e 1.1.251 -DTRS -b tpuarts:/dev/ttyAMA0"

knxd.service and knxd.socket work correctly

**Comment by smurfix** [comment] 2016-10-10 21:26
On 10.10.2016 23:12, mclane wrote:
> typically in the high area (>30 000) 

What does "lsof -p pid-of-knxd" say? There should be two open UDP ports,
a high-numbered one and 3671.
Something like this:

knxd    1104 knxd    9u  IPv4      16744      0t0    UDP *:38660 

knxd    1104 knxd   10u  IPv4      16745      0t0    UDP *:3671 


If so, knxd probably sends the wrong port in its announcement multicast.
Easy enough to fix (I hope ;-).

Also ETS5 should work when you set it to multicase mode, i.e. you
'connect' to your Windows machine's network interface instead of knxd. True?

-- 
-- Matthias Urlichs

**Comment by mclane** [comment] 2016-10-11 17:26
Good evening,

indeed, lsof shows (among a lot of other stuff) 2 UDP ports:

knxd    451 knxd    8u  IPv4      10260      0t0   UDP *:51685 
knxd    451 knxd    9u  IPv4      10261      0t0   UDP *:3671

And ETS5 works if I connect to the Windoofs machine network interface (even Busmonitor is ok).

If you need further data, just let me know.

**Comment by smurfix** [comment] 2016-10-11 18:24
Thanks, that should be sufficient for fixing the problem. I'll have a look.

NB: the reason for using two ports is that I need them in order to handle machine-local communication. If there are two knxd(-ish) processes running on one system, they should be able to see each other's multicast packets.

**Comment by mclane** [comment] 2016-10-11 19:16
Another problem found:

ETS5 programming does not work when connected via Windows network connection (operation times out); line scan detects only one (out of 4) devices in my test installation (the one with the highest physical address). Apparently, all operations which require writing to the bus do not work (even retrieving device information). Maybe this is linked to the problem above?

**Comment by mclane** [comment] 2016-10-12 18:48
Good evening,

in the mean time I have reinstalled the stable branch and it works again.

lsof only shows one open UDP port (namely 3671). ETS5 works again as previously; however, the Bus Monitor function generates frame errors (which was the reason why I tried the master branch).

**Comment by netsinn** [comment] 2016-10-25 10:50
I have the same issue. ETS5 does not recognize port 3671, but only the higher (changing) one.

Is there a fix for this?

Thanks a lot for your great work!

**Comment by smurfix** [comment] 2016-11-09 11:39
Please check branch p156.

**Comment by mclane** [comment] 2016-11-09 20:59
will try on the weekend probably

**Comment by TravelAndy** [comment] 2016-11-13 20:19
Hello,
I installed the branch p156 today. Still have the same problem of changing port numbers in ETS5.
Is there any workaround until this issue is fixed?

**Comment by smurfix** [comment] 2016-11-13 20:29
On 13.11.2016 21:19, TravelAndy wrote:
> I installed the branch p156 today. Still have the same problem of
> changing port numbers in ETS5.
> Is there any workaround until this issue is fixed?
Yes. "Connect" to the computer's network interface in ETS. That'll
switch to multicast.

-- 
-- Matthias Urlichs

**Comment by smurfix** [comment] 2016-12-09 14:44
Looks like a duplicate of #167.

**Closed** 2017-01-19 15:55 UTC
Labels: duplicate
