### ISSUE TITLE
branch next: does not compile with --without-libstdc

### ISSUE THREAD

**Issue by tru7** [knxd/knxd#81] opened 2015-07-28 19:47 UTC
compiling code from branch next fails with configure option --without-libstdc.
I don't know if I should be happy when being urged to link with libstdc++ when this library is bigger than knxd binary and therefore doubling size on small flash rom. I think this change should be discussed.

**Comment by smurfix** [comment] 2015-07-28 21:26
I agree that it'd be nice not to require libstdc++. The problem is keeping track of the references to layer2 objects, which is necessary because layer3 now needs data from the source driver (specifically, the address that was assigned to the remote side). In the master branch the code only requires a unique object pointer and does not care if that pointer is stale.

One possible workaround is to move the layer3 code which changes a packet based on the source Layer2 object (i.e. fill in the source address) to Layer3::recv_L_Data(). Then, use a distinct Layer2 ID (increment a counter …) instead of relying on the object's address. Would you like to implement that?

Also, while we're on the topic of memory management: there are a couple of places where we should use (const) references to packets, not copy them unnecessarily.

**Comment by tru7** [comment] 2015-07-29 16:55
I would like to help but I have absolutely no clue about coding, I don't even understand the source code written. I really admire your work but all I'm capable is doing the compilation on different platforms and do some testing with different devices in my home environment.

**Comment by smurfix** [comment] 2016-10-11 07:19
Closing this for now. Some food for the TODO list copied.

**Closed** 2016-10-11 07:19 UTC
