### ISSUE TITLE
Assertion `akt != 0' failed.

### ISSUE THREAD

**Issue by knowthelist** [knxd/knxd#173] opened 2016-12-03 10:43 UTC
mario@raspberrypi:~ knxtool groupswrite ip:192.168.178.15 1/1/2 0
Send request
mario@raspberrypi:~ $ sudo tail -f /var/log/daemon.log 
Dec  3 11:33:07 raspberrypi systemd[1]: Listening on KNX Daemon (socket).
Dec  3 11:33:07 raspberrypi systemd[1]: Starting KNX Daemon...
Dec  3 11:33:07 raspberrypi systemd[1]: Started KNX Daemon.
Dec  3 11:33:07 raspberrypi systemd[1]: Reloading.
Dec  3 11:33:07 raspberrypi systemd[1]: Reloading.
Dec  3 11:33:07 raspberrypi systemd[1]: Started KNX Daemon.
Dec  3 11:33:08 raspberrypi systemd[1]: Reloading.
Dec  3 11:33:17 raspberrypi systemd[1]: Stopping KNX Daemon...
Dec  3 11:33:17 raspberrypi systemd[1]: Starting KNX Daemon...
Dec  3 11:33:17 raspberrypi systemd[1]: Started KNX Daemon.
Dec  3 11:35:25 raspberrypi knxd[20592]: knxd: queue.h:110: const T& Queue<T>::top() const [with T = Array<unsigned char>]: Assertion `akt != 0' failed.
Dec  3 11:35:25 raspberrypi systemd[1]: knxd.service: main process exited, code=killed, status=6/ABRT
Dec  3 11:35:25 raspberrypi systemd[1]: Unit knxd.service entered failed state.
Dec  3 11:35:35 raspberrypi systemd[1]: knxd.service holdoff time over, scheduling restart.
Dec  3 11:35:35 raspberrypi systemd[1]: Stopping KNX Daemon...
Dec  3 11:35:35 raspberrypi systemd[1]: Starting KNX Daemon...
Dec  3 11:35:35 raspberrypi systemd[1]: Started KNX Daemon.
^Cmario@raspberrypi:~ /usr/bin/knxd --version
knxd 0.11.9
mario@raspberrypi:~ $

**Comment by knowthelist** [comment] 2016-12-03 11:08
No issue if I use knxd 0.10.0 (stable branch) & ETS 5.5.1 (build 575)

**Comment by knowthelist** [comment] 2016-12-03 11:11
I use TUL stick
Bus 001 Device 004: ID 03eb:204b Atmel Corp. LUFA USB to Serial Adapter Project
conf:
KNXD_OPTS="-e 1.1.250 -u /tmp/eib -D -T -R -S -b tpuarts:/dev/ttyKNX1"

**Comment by stmichaelis** [comment] 2016-12-08 20:27
Looks like a duplicate of Bug #166.

**Closed** 2017-01-19 15:55 UTC
Labels: duplicate
