### ISSUE TITLE
Issues with ETS5 after change to 0.11

### ISSUE THREAD

**Issue by duenengeist** [knxd/knxd#180] opened 2016-12-14 01:00 UTC
Hi all,

I changed knxd from 0.10 to 0.11. Since then I am having problem with ETS5. The connection test is OK, but line-scan shows no devices, no reading or writing of KNX-devices is possible. It worked fine with 0.10.

I start Kknxd with: knxd -t1023  -e 1.1.251  tpuarts:/dev/ttyAMA0 -i -D -T -S
I use a PI with ROT by busware
I have ETS5.5.2 (Build 665)

ETS5 shows timeout when reading or programming a device: "Das Gerät antwortet nicht in angemessener Zeit"

I have alos tried the Multicast-Setup like this:
knxd -p /run/knxd/knxd.pid --eibaddr=1.1.251 -D -T -R -S  --trace=5 --error=5 --listen-local=/tmp/knx tpuarts:/dev/ttyAMA0
This find two out of 17 devices during line-scan. Reading or programming of these devices times out (as above)

I also run FHEM, which works fine with the first config but not the second.

Any ideas? What else can I try to debug?

Viele Grüße,

Carsten

**Comment by duenengeist** [comment] 2016-12-14 09:10
Hi all,

i went back to 0.10 (this was a hard time as an relatively linux-noob, will have to read some books over Christmas...) and it works fine just as before.

Carsten

**Comment by smurfix** [comment] 2016-12-14 09:18
I'll try to (finally) find the problem over the holidays.

**Comment by geertge** [comment] 2016-12-16 12:52
I have the same problem using a Siemens IP gateway. I installed the latest Raspberry PI image from SmarthomeNG. I don't know which version of knxd I have. How can I check it?

Geert

**Comment by smurfix** [comment] 2016-12-16 15:34
```
# src/server/knxd -V
knxd 0.11.14
```

**Comment by geertge** [comment] 2016-12-16 15:57
Thanks Matthias,

I see that I still have the version 0.10. So I have to upgrade to the latest version. I hope I will find some instruction on the internet how to do.

Thanks,


Geert



Van: Matthias Urlichs [mailto:notifications@github.com]
Verzonden: vrijdag 16 december 2016 16:34
Aan: knxd/knxd <knxd@noreply.github.com>
CC: geertge <hans_geert@msn.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [knxd/knxd] Issues with ETS5 after change to 0.11 (#180)


# src/server/knxd -V

knxd 0.11.14

**Comment by elupus** [comment] 2016-12-16 23:29
@smurfix i suspect the change i did in https://github.com/knxd/knxd/pull/181 for considering the backend as a bus could be what is needed here too. I could see any other way (unless the device have sent a group message) for physical requests to be routed out.

Seems that was dropped with the removal of has_bus() function.

**Comment by duenengeist** [comment] 2016-12-18 23:39
Hi, 
let me know if there is anything I can test with 0.11. I currently run to programm a couple of things in my installation, but over christmas Ican go back to 0.11 to test...

**Comment by smurfix** [comment] 2016-12-19 00:07
I have successfully programmed with ETS5 in multicast mode with the current master version.

**Comment by duenengeist** [comment] 2016-12-20 18:04
Ok, I will try during the next days..

**Comment by Iktek** [comment] 2017-01-07 13:41
I'm trying to do an KNX-connection with pigator TPUART and ETS5 with the current master, unfortunately this also doesn't work as described above. 

Basically knxd is configured as follows:
KNXD_OPTS="-t 1023 -e 1.1.127 -E 1.1.120:126 -f 9 -DTRS --layer2=tpuarts:/dev/ttyKNX1"

When trying to get the "unprogrammed devices", knxd does the following

`Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 3 [3:layer3               98.583] Enqueue L_Data system from 1.1.125 to 0/0/0 hops: 06 T_DATA_XXX_REQ A_IndividualAddress_Read
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 1 [2:mcast                98.583] Send(004): 04 01 09 00
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 0 [2:mcast                98.584] Send(010): 06 10 04 21 00 0A 04 01 09 00
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 3 [3:layer3               98.584] RecvData L_Data system from 1.1.125 to 0/0/0 hops: 05 T_DATA_XXX_REQ A_IndividualAddress_Read
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 8 [2:mcast                98.584] Send_Route L_Data system from 1.1.125 to 0/0/0 hops: 05 T_DATA_XXX_REQ A_IndividualAddress_Read
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 1 [2:mcast                98.584] Send(011): 29 00 B0 D0 11 7D 00 00 01 01 00
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 2 [4:tpuarts:/dev/ttyKNX1 98.584] Send L_Data system from 1.1.125 to 0/0/0 hops: 05 T_DATA_XXX_REQ A_IndividualAddress_Read
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 0 [2:mcast                98.584] Send(017): 06 10 05 30 00 11 29 00 B0 D0 11 7D 00 00 01 01 00
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 0 [4:tpuarts:/dev/ttyKNX1 98.584] Write(018): 80 B0 81 11 82 7D 83 00 84 00 85 D1 86 01 87 00 48 F3
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 0 [2:mcast                98.584] Dropped(017): 06 10 05 30 00 11 29 00 B0 D0 11 7D 00 00 01 01 00
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 0 [4:tpuarts:/dev/ttyKNX1 98.606] RecvB(008): B0 11 7D 00 00 D1 01 00
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 0 [4:tpuarts:/dev/ttyKNX1 98.606] Ignoring this telegram. We sent it.
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 0 [4:tpuarts:/dev/ttyKNX1 98.609] RecvB(001): F3
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 0 [4:tpuarts:/dev/ttyKNX1 98.609] Ignoring this telegram. We sent it.
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 0 [4:tpuarts:/dev/ttyKNX1 98.612] RecvB(001): 8B
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 0 [4:tpuarts:/dev/ttyKNX1 98.631] RecvB(008): B0 FF FF 00 00 E1 01 40
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 0 [4:tpuarts:/dev/ttyKNX1 98.631] SendAck 11
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 0 [4:tpuarts:/dev/ttyKNX1 98.634] RecvB(001): EF
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 1 [4:tpuarts:/dev/ttyKNX1 98.634] RecvLP(009): B0 FF FF 00 00 E1 01 40 EF
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 3 [3:layer3               98.634] Enqueue L_Data system from 15.15.255 to 0/0/0 hops: 06 T_DATA_XXX_REQ A_IndividualAddress_Response
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 3 [3:layer3               98.635] RecvData L_Data system from 15.15.255 to 0/0/0 hops: 05 T_DATA_XXX_REQ A_IndividualAddress_Response
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 8 [2:mcast                98.635] Send_Route L_Data system from 15.15.255 to 0/0/0 hops: 05 T_DATA_XXX_REQ A_IndividualAddress_Response
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 1 [2:mcast                98.635] Send(011): 29 00 B0 D0 FF FF 00 00 01 01 40
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 0 [2:mcast                98.635] Send(017): 06 10 05 30 00 11 29 00 B0 D0 FF FF 00 00 01 01 40
Jan 07 13:24:20 raspberrypi knxd[1189]: Layer 0 [2:mcast                98.635] Dropped(017): 06 10 05 30 00 11 29 00 B0 D0 FF FF 00 00 01 01 40
Jan 07 13:24:21 raspberrypi knxd[1189]: Layer 8 [13:mcast:1.1.125        99.508] TunnelSend 1
Jan 07 13:24:21 raspberrypi knxd[1189]: Layer 1 [2:mcast                99.508] Send(015): 04 01 00 00 29 00 B0 D0 FF FF 00 00 01 01 40
Jan 07 13:24:21 raspberrypi knxd[1189]: Layer 0 [2:mcast                99.508] Send(021): 06 10 04 20 00 15 04 01 00 00 29 00 B0 D0 FF FF 00 00 01 01 40
Jan 07 13:24:21 raspberrypi knxd[1189]: Layer 0 [2:mcast                99.594] Recv(016): 06 10 02 09 00 10 01 00 08 01 C0 A8 1E 86 D6 C6
Jan 07 13:24:21 raspberrypi knxd[1189]: Layer 1 [2:mcast                99.594] Recv(010): 01 00 08 01 C0 A8 1E 86 D6 C6
Jan 07 13:24:21 raspberrypi knxd[1189]: Layer 3 [3:layer3               99.594] deregisterLayer2 13:mcast:1.1.125 = 1
Jan 07 13:24:21 raspberrypi knxd[1189]: Layer 8 [2:mcast                99.594] CloseS
Jan 07 13:24:21 raspberrypi knxd[1189]: Layer 1 [2:mcast                99.594] Send(002): 01 00
Jan 07 13:24:21 raspberrypi knxd[1189]: Layer 0 [2:mcast                99.594] Send(008): 06 10 02 0A 00 08 01 00
`

I really don't know if this is related to the bug above or if it is just an configuration issue, but I would appreciate your help.
Regards Pascal

**Comment by smurfix** [comment] 2017-01-07 13:55
You are apparently not using broadcast mode in ETS5 (bind to the interface).
Tunneling through knxd does not work with master du to what appears to be a bug in ETS5 which I'll probably have to add a workaround for.

Incidentally, `-e 1.1.127 -E 1.1.120:126` doesn't work like it should because knxd's address is within the range you're allocating an I don't skip that. Please use `-E 1.1.128:118`.

**Comment by Iktek** [comment] 2017-01-07 14:01
Thanks smurfix for your quick answer.. But how do I configure ETS5 (now 5.5.3) to use broadcast-mode?

**Comment by smurfix** [comment] 2017-01-07 14:05
You set it to talk to the interface, not to the computer that's running knxd.

**Comment by Iktek** [comment] 2017-01-07 17:46
Hi Matthias,

Sorry to bother you again, but the knxd connection is still not really 
working.

I managed to get a first Adress-programming of a device but this one has 
aborted.

Now the device seems to have address 1.1.1 ( An ETS line-scan shows that 
device), but I can neither program an application, nor unload the 
address from that device.

On debug-output I still get dropped packets.

It doesn't even matter if I program the host-adress of ets to an adress 
in the same line or not.
Is there some further guide to know how to configure that setup right?

ETS -> WIFI -> RPI with knxd -> TPUART -> KNX-Device

In appendix my current log-output:

Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 0 [2:mcast                
290.852] Recv(017): 06 10 05 30 00 11 29 00 B0 60 11 7D 11 01 01 43 00
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 1 [2:mcast                
290.853] Recv(011): 29 00 B0 60 11 7D 11 01 01 43 00
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 8 [2:mcast                
290.853] Recv_Route L_Data system from 1.1.125 to 1.1.1 hops: 06 
T_DATA_CONNECTED_REQ serno:00 A_DeviceDescriptor_Read Type:00
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 3 [3:layer3               
290.853] Enqueue L_Data system from 1.1.125 to 1.1.1 hops: 06 
T_DATA_CONNECTED_REQ serno:00 A_DeviceDescriptor_Read Type:00
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 3 [3:layer3               
290.853] RecvData L_Data system from 1.1.125 to 1.1.1 hops: 05 
T_DATA_CONNECTED_REQ serno:00 A_DeviceDescriptor_Read Type:00
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 2 [4:tpuarts:/dev/ttyKNX1 
290.853] Send L_Data system from 1.1.125 to 1.1.1 hops: 05 
T_DATA_CONNECTED_REQ serno:00 A_DeviceDescriptor_Read Type:00
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 0 [4:tpuarts:/dev/ttyKNX1 
290.853] Write(018): 80 B0 81 11 82 7D 83 11 84 01 85 51 86 43 87 00 48 21
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 0 [4:tpuarts:/dev/ttyKNX1 
290.856] RecvB(008): B0 11 01 11 7D 63 43 40
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 0 [4:tpuarts:/dev/ttyKNX1 
290.856] SendAck 11
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 0 [4:tpuarts:/dev/ttyKNX1 
290.862] RecvB(003): 07 05 51
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 1 [4:tpuarts:/dev/ttyKNX1 
290.862] RecvLP(011): B0 11 01 11 7D 63 43 40 07 05 51
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 3 [3:layer3               
290.862] Enqueue L_Data system from 1.1.1 to 1.1.125 hops: 06 
T_DATA_CONNECTED_REQ serno:00 A_DeviceDescriptor_Response Type:00  
Descriptor: 0705
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 3 [3:layer3               
290.862] RecvData L_Data system from 1.1.1 to 1.1.125 hops: 05 
T_DATA_CONNECTED_REQ serno:00 A_DeviceDescriptor_Response Type:00  
Descriptor: 0705
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 8 [2:mcast                
290.862] Send_Route L_Data system from 1.1.1 to 1.1.125 hops: 05 
T_DATA_CONNECTED_REQ serno:00 A_DeviceDescriptor_Response Type:00  
Descriptor: 0705
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 1 [2:mcast                
290.862] Send(013): 29 00 B0 50 11 01 11 7D 03 43 40 07 05
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 0 [2:mcast                
290.863] Send(019): 06 10 05 30 00 13 29 00 B0 50 11 01 11 7D 03 43 40 07 05
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 0 [2:mcast                
290.863] Dropped(019): 06 10 05 30 00 13 29 00 B0 50 11 01 11 7D 03 43 
40 07 05
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 0 [4:tpuarts:/dev/ttyKNX1 
290.876] RecvB(008): 90 11 01 11 7D 63 43 40
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 0 [4:tpuarts:/dev/ttyKNX1 
290.876] SendAck 11
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 0 [4:tpuarts:/dev/ttyKNX1 
290.882] RecvB(003): 07 05 71
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 1 [4:tpuarts:/dev/ttyKNX1 
290.882] RecvLP(011): 90 11 01 11 7D 63 43 40 07 05 71
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 3 [3:layer3               
290.882] Enqueue L_Data (repeated) system from 1.1.1 to 1.1.125 hops: 06 
T_DATA_CONNECTED_REQ serno:00 A_DeviceDescriptor_Response Type:00  
Descriptor: 0705
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 3 [3:layer3               
290.882] Repeated discareded
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 0 [4:tpuarts:/dev/ttyKNX1 
290.899] RecvB(008): B0 11 7D 11 01 51 43 00
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 0 [4:tpuarts:/dev/ttyKNX1 
290.899] Ignoring this telegram. We sent it.
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 0 [4:tpuarts:/dev/ttyKNX1 
290.902] RecvB(001): 21
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 0 [4:tpuarts:/dev/ttyKNX1 
290.902] Ignoring this telegram. We sent it.
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 0 [4:tpuarts:/dev/ttyKNX1 
290.904] RecvB(001): 8B
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 0 [4:tpuarts:/dev/ttyKNX1 
290.922] RecvB(008): B0 11 01 11 7D 60 C2 91
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 0 [4:tpuarts:/dev/ttyKNX1 
290.922] SendAck 11
Jan 07 17:39:44 raspberrypi knxd[1173]: Layer 1 [4:tpuarts:/dev/ttyKNX1 
290.922] RecvLP(008): B0 11 01 11 7D 60 C2 91

Thanks in advance,

Regards Pascal

Am 07.01.2017 um 15:05 schrieb Matthias Urlichs:

**Comment by duenengeist** [comment] 2017-01-07 18:30
Hi Pascal,

I was sick, so I could not try 0.11 again, I am still on 0.10 which works fine for me.

Redgarding ETS5:

I do not know if it makes a difference, but there is a newer version of ETS, I am running 5.5.3 build 871

maybe you can post your "schnittstellen" setting in ETS?

Carsten

**Comment by Iktek** [comment] 2017-01-07 19:03
You're right.. 0.10 is working with ets 5 and tunnel-mode!

So something seems still to be wrong with 0.11

If I should test a new version of 0.11 lateron, please let me know.

Regards Pascal

Am 07.01.2017 um 19:30 schrieb Carsten:

**Comment by smurfix** [comment] 2017-01-07 19:40
Apparently, ETS5 ignores some packets because it wants them to come from the broadcast port instead of the port that knxd advertises. This appears to be a bug in ETS5, there's a bug report open on it whose number I can't find at the moment.

I'll probably have add a compatibility flag. Using separate ports is unfortunately necessary for running multiple knx programs (not just knxd) on the same host …

**Comment by smurfix** [comment] 2017-01-07 19:42
If you want to help further, (a) wait for the patch to 0.11/0.12 that adds the --single-port flag, (b) if that still doesn't help, run wireshark and compare the packets from 0.12 with those from 0.10.

**Comment by Caprisna** [comment] 2017-01-07 22:36
Hi,
have the same problem here, tried to programming in ETS5 with v0.11 but getting timeouts all the time. I tried with broadcast server as well as with tunneling both with no success.
I am downgrading now to 0.10 till your patch/new stable release is available

**Comment by elupus** [comment] 2017-01-07 23:05
does the timeout happen after a while, ie progressbar has moved a bit? or
directly on start of programming?

**Comment by Caprisna** [comment] 2017-01-08 10:22
progressbar makes no progress, so after some seconds...
With luck i was able to programm 1 device, but immediately aftewards i tried it agains and then it failed again.

**Comment by Caprisna** [comment] 2017-01-12 20:33
I found out, that the problem occurs just, when i run knxtools vbusmonitor1.
Without running any commands, i was able to program via Multicast server. With the fork of stmichaels v0.10 i am also able to program via ip interface

**Comment by smurfix** [comment] 2017-01-23 03:00
Something else must be going on. Running vbusmonitor1 changes absolutely nothing, other than copy your packets to the monitor of course.

Please test the current 0.12.

**Comment by ledlinge** [comment] 2017-01-25 19:10
Hi,
issue is still reproducible using version 0.12.4.
I've captured wireshark traces for working and non-working version, sent to you via e-mail.

**Comment by smurfix** [comment] 2017-01-30 17:06
Does this still happen with 0.12.6?

**Comment by ledlinge** [comment] 2017-01-31 18:43
Unfortunately it doesn't work with 0.12.6 either. Same behaviour is seen. 
Setting in /etc/knxd.conf is KNXD_OPTS="-e 1.0.251 -E 0.0.2:8 -D -T -R -S -c -b tpuarts:/dev/ttyAMA0"

**Comment by smurfix** [comment] 2017-02-01 01:51
Should be fixed in 5930996

**Comment by smurfix** [comment] 2017-02-01 10:41
Meh. Please add -t1022 in front and send me the log(s).

**Comment by dallmair** [comment] 2024-12-15 01:03
This exchange is almost 8 years old, and no log added. Also, the versions 0.11 and 0.12 are extremely old, and programming works fine in current versions -- although it still requires the "single port" workaround (default atm) and the "single" filter in pretty much every case (at least I never got it to work without these).

Anyway, time to close this issue.

**Closed by dallmair** 2024-12-15 01:03 UTC
Labels: waiting for feedback
