### ISSUE TITLE
Cometvisu does NOT work with any current KNXD if any non-readable GA is present in request- eibread-cgi problem

### ISSUE THREAD

**Issue by MGKQB** [knxd/knxd#352] opened 2018-07-09 10:13 UTC
when requesting values with eibread-cgi asking for a single value the script returns lots of values? When asking for multiple values a timeout occurs (request take more than 10 seconds to complete) - this should come from cache.

**Comment by grzlhmpf** [comment] 2018-07-09 13:25
KNXD latest version, build on Debian 9 with the (btw excellent) instructions here.

curl -vv "http://192.168.1.3/cgi-bin/r?t=60&s=SESSION&a=4/3/15" should return this value from the cache, but lots or (seemingly random) values are returned. It also takes a LONG time for values which are supposed to come from cache (about 3 seconds!)

/usr/lib/cgi-bin/r is a symbolic link to eibread-cgi (also build from the latest master git version.) 

IMHO the problem is timeout related and/or the cache does not work or is not used.

i also posted  on https://knx-user-forum.de/forum/projektforen/knxd/1241265-knxd-cometvisu-eibread-probleme

**Comment by grzlhmpf** [comment] 2018-07-11 08:40
I did further testing. When I call the eibread-cgi with a longer timeout (like 60 seconds) the call returns data after 12 seconds for my environment.

there seem to be two strange behaviors in eibread-cgi
1) any non-readable GA in the request takes a long time to complete and runs into a timeout - an empty response is returned. Is this behavior intended? IMHO non-readable GAs should be skipped not returning values, but not with a long timeout. Just grab the value from cache, is it is not there, skip the GA.
2) there are a lot of additional GAs in the response?

**Comment by grzlhmpf** [comment] 2018-07-11 18:29
reading the source I noticed "EIB_Cache_Read_Sync" is used to read all values. If I understand the code correctly (I probably don't) this could create the large response time I see when non-readable GA are requested because the script is waiting there for a response which will never arrive.

Does this behavior make sense? IMHO the script should send a read request if the value is not in the cache but not wait for the response, just for the sake of populating the cache for the next call - the CometVisu is requesting all those values frequently anyway.

Suggestion: change line 306 to EIB_Cache_Read

this is separate from the "lots of additional GAs no-one asked for are returned" but could solve the timeout problem.

**Comment by grzlhmpf** [comment] 2018-08-01 08:34
expected behaviour explained here (in German): 
https://knx-user-forum.de/forum/supportforen/cometvisu/1245287-cometvisu-ohne-knxd-eibd?p=1246783#post1246783

**Comment by dallmair** [comment] 2018-09-17 23:55
OK, so I've looked into this:
1. Large response times: I suspect you're using a USB adapter, and there are already several issues regarding slow USB responses, so I'd rather not tackle this within this issue. Definitely something to look into, but it affects much more than just eibread-cgi.
2. Large response times, take 2: The server should probably indeed send these read PDUs asynchronously. A single paced filter or slow device should not have a noticeable effect on the visu, IMHO. Not sure how to tackle this though -- @smurfix: Any guidance on this/would you be able to take a look?
3. Additional GAs in response plus other broken behavior: Should be fixed with inclusion of the PR I created a few minutes ago.

**Comment by dallmair** [comment] 2018-09-18 07:10
Addendum to number 2 above: EIB_Cache_Read_Sync sends a read PDU, EIB_Cache_Read does not. Therefore, the code is correct from my point of view.

It iterates over all addresses, requesting those values from the bus that it doesn't know about yet, in the first loop (only if i==0, i.e. on CometVisu's first request). In later requests it just returns data from the cache and does not cause any bus traffic anymore. This makes sense as you don't want a spurious unused group address to spam your KNX bus on every visu update.

**Closed** 2018-11-22 20:38 UTC

**Comment by lassos** [comment] 2020-12-05 14:52
same here. latest cometvisu with knxd  and debian buster. also not working
