### ISSUE TITLE
Cannot build on Ubuntu 15.04

### ISSUE THREAD

**Issue by marcopiraccini** [knxd/knxd#86] opened 2015-08-24 20:33 UTC
When I run: `dpkg-buildpackage -b` the result is:

(...)
dpkg-buildpackage: binary-only upload (no source included)
 signfile knxd_0.10.0-1_amd64.changes
gpg: skipped "Matthias Urlichs <matthias@urlichs.de>": secret key not available
gpg: dpkg-sign.HgaHCGFv/knxd_0.10.0-1_amd64.changes: clearsign failed: secret key not available

**Comment by smurfix** [comment] 2015-08-24 20:47
Not a bug. The package has been built. If you don't like the error
message, use the "-uc" flag.

On 24.08.2015 22:33, Marco wrote:
>
> When I run: |dpkg-buildpackage -b| the result is:
>
> (...)
> dpkg-buildpackage: binary-only upload (no source included)
> signfile knxd_0.10.0-1_amd64.changes
> gpg: skipped "Matthias Urlichs matthias@urlichs.de
> <mailto:matthias@urlichs.de>": secret key not available
> gpg: dpkg-sign.HgaHCGFv/knxd_0.10.0-1_amd64.changes: clearsign failed:
> secret key not available
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/knxd/knxd/issues/86>.
>


-- 
-- Matthias Urlichs

**Comment by smurfix** [comment] 2015-08-24 20:48
fixed in a241b3d

**Closed by smurfix** 2015-08-24 20:48 UTC
