### ISSUE TITLE
knxd hangs after a while

### ISSUE THREAD

**Issue by Morg42** [knxd/knxd#58] opened 2015-04-06 22:35 UTC
After compiling and packaging knxd 0.9.0-1 on Debian 7.8 i386 and armhf (RasPi B), it started hanging after some time (approx 3-4 hrs).

top shows 68 - 95 % cpu time on knxd, debug output appended. kill / ctrl-c is ignored, kill -9 works.

Layer 8(086D24C0,5522EF5B) LastUpdates start: 339 pos: 339
Layer 8(086E6238,5522EF5B) SendMessage(004): 00 76 01 53
Layer 8(086E6238,5522EF5B) RecvMessage(005): 00 76 01 53 2C
Layer 8(086D24C0,5522EF5B) LastUpdates start: 339 pos: 339
Layer 8(086D24C0,5522EF62) LastUpdates start: 339 pos: 339
Layer 8(086E6678,5522EF62) SendMessage(004): 00 76 01 53
Layer 8(086E6678,5522EF62) RecvMessage(005): 00 76 01 53 2C
Layer 8(086D24C0,5522EF62) LastUpdates start: 339 pos: 339
Layer 0(086B1D30,5522EF69) Recv(016): 06 10 02 07 00 10 01 00 08 01 00 00 00 00 00 00
Layer 1(086B1D30,5522EF69) Recv(010): 01 00 08 01 00 00 00 00 00 00
Layer 1(086B1D30,5522EF69) Send(002): 01 00
Layer 0(086B1D30,5522EF69) Send(008): 06 10 02 08 00 08 01 00
Layer 8(086D24C0,5522EF6B) LastUpdates start: 339 pos: 339
Layer 8(086E64E0,5522EF6B) SendMessage(004): 00 76 01 53
Layer 8(086E64E0,5522EF6B) RecvMessage(005): 00 76 01 53 2C
Layer 8(086D24C0,5522EF6B) LastUpdates start: 339 pos: 339
Layer 8(086D24C0,5522EF74) LastUpdates start: 339 pos: 339
Layer 8(086E6468,5522EF74) SendMessage(004): 00 76 01 53
Layer 8(086E6468,5522EF74) RecvMessage(005): 00 76 01 53 2C
Layer 8(086D24C0,5522EF74) LastUpdates start: 339 pos: 339
Layer 1(08660668,5522EF76) Heartbeat
Layer 1(08660B30,5522EF76) Send(010): 15 00 08 01 C0 A8 02 01 0E 58
Layer 0(08660B30,5522EF76) Send(016): 06 10 02 07 00 10 15 00 08 01 C0 A8 02 01 0E 58
Layer 0(08660B30,5522EF76) Recv(008): 06 10 02 08 00 08 15 00
Layer 1(08660B30,5522EF76) Recv(002): 15 00
Layer 0(086B1D30,5522EF78) Recv(016): 06 10 02 07 00 10 01 00 08 01 00 00 00 00 00 00
Layer 1(086B1D30,5522EF78) Recv(010): 01 00 08 01 00 00 00 00 00 00
Layer 1(086B1D30,5522EF78) Send(002): 01 00
Layer 0(086B1D30,5522EF78) Send(008): 06 10 02 08 00 08 01 00
Layer 8(086D24C0,5522EF7B) LastUpdates start: 339 pos: 339
Layer 8(086E6860,5522EF7B) SendMessage(004): 00 76 01 53
Layer 8(086E6860,5522EF7B) RecvMessage(005): 00 76 01 53 2C
Layer 8(086D24C0,5522EF7B) LastUpdates start: 3

**Comment by Makki1** [comment] 2015-04-06 22:50
Lets guess:
- a USB interface?

Please check/fix the power supply of the RPi and post dmsg, startup-params..

I guess its # 1, the unusable USB power-supply on the RPi and/or the the already known bug after a USB dis/re-connect.

**Comment by Morg42** [comment] 2015-04-06 22:55
Sorry - no :)
RPi is powered by a dedicated USB power source (Hutschienentrafo 5V 2,4A); additionally this also happens on a "normal" i386 PC.
I removed the "using IP interface" from the title - my bad. Using MDT IP interface via IPT:.

**Comment by Makki1** [comment] 2015-04-06 23:10
Ok, but still missing the exact parameters? As many details as possible to reproduce it. Sorry but its working on thousand systems for many years, so we need an idea why..

**Comment by Morg42** [comment] 2015-04-06 23:51
knxd source cloned from https://github.com/knxd/knxd, built with dpkg-buildpackages, default compile options; built against libusb-1.0-0 (1.0.11) from Debian repository and pthsem 2.0.8 compiled from mkoegler's sources.
run args are "-c -d -S -D -R -T -i -u --no-tunnel-client-queuing ipt:192.168.2.232". ETS connects via IP, eibread-cgi/eibwrite-cgi connect via /tmp/eib.
hangs both on RasPi B, Raspbian (Debian 7.8) and LG X110 (Netbook with Atom N270; Debian 7.8). Did not have problems with eibd 0.0.4+nmu18 packages from wiregate repo or self compiled from bcusdk 0.0.5.
The knxd log (see above) seems to hang in mid-output. Up to now reproducable. Currently I'm using ETS to program hardware / monitor bus activity and modifying my CometVisu config. All in all I have about 125 GA, most of which are used in CometVisu (half switch/action, half status info).

What else do you need? I'm not sure where to look, especially because it doesn't run after switching from eibd to knxd. eibd packages / files were removed before installing knxd.

**Comment by cribskip** [comment] 2015-05-19 15:52
This seems to be related to #10 as far as CPU load is concerned.

**Comment by smurfix** [comment] 2015-05-20 07:31
#10 looped in a condition variable but was otherwise useable, while this hangs somewhere not involving thread switching and can only be killed with -9.

@Morg42 : Please attach to the "hung" knxd with gdb and provide a stack trace. Details how to do that are in #10, in case you don't habitually do that.

**Comment by smurfix** [comment] 2015-07-05 17:29
Any progress? Does this still happen with current master?

**Comment by smurfix** [comment] 2015-07-24 01:41
Closing due to no feedback and "works here".
Please re-open if you have more information.

**Closed by smurfix** 2015-07-24 01:41 UTC
