### ISSUE TITLE
KNXD doesn't work with Busch-Jäger USB interface 6123

### ISSUE THREAD

**Issue by cornelw** [knxd/knxd#124] opened 2016-02-08 13:47 UTC
Hi,
I'm using Debian Jessie lite and installed knxd with the following script:
# !/bin/bash

//# first, install build tools and get the source code
sudo apt-get install git-core build-essential debhelper cdbs autoconf automake libtool libusb-1.0-0-dev libsystemd-daemon-dev dh-systemd
git clone https://github.com/knxd/knxd.git
 //# knxd requires libpthsem which unfortunately isn't part of Debian
wget --no-check-certificate https://www.auto.tuwien.ac.at/~mkoegler/pth/pthsem_2.0.8.tar.gz
tar xzf pthsem_2.0.8.tar.gz
cd pthsem-2.0.8
dpkg-buildpackage -b -uc
cd ..
sudo dpkg -i libpthsem_.deb
//# now build+install knxd itself
cd knxd
dpkg-buildpackage -b -uc
cd ..
sudo dpkg -i knxd__.deb knxd-tools_*.deb
//# some important changes
//# Modify /boot/cmdline.txt to disable boot screen over serial interface
sed -e's/ console=ttyAMA0,115200//g' /boot/cmdline.txt --in-place=.bak
sed -e's/ kgdboc=ttyAMA0,115200//g' /boot/cmdline.txt --in-place=.bak
//# Disable serial console
systemctl disable serial-getty@ttyAMA0.service

**Since I use knxd my usb Interface 6123-USB from Busch-Jäger does not work any longer.**
**As I used the outdated eib daemon (bcusdk_0.0.5) with cEMI-patch evrything works fine, except the high cpu usage of about 99%. vbusmonitor1 and groupswrite were successful, e. g. lights can be switched using "groupswrite 0/0/47 1".**

**Can anybody help here?**
**Does anybody have a working example (KNXD_OPTS) by using an usb Interface?**

**Thank you in advance!**
**Cornel**

I called eibd with the following Options:
EIBD_OPTIONS="-d -D -T -R -S -i -u --eibaddr=1.1.128 usb:1:5:1:0:0"
groupswrite was working successfully.

When I start knxd manually with the following Options, everything seems to be working.
KNXD_OPTS="-e 1.1.128 -t1023 -f9 -DTRS -b usb:1:5:1:0:0"

Here is the console Output:

root@automation1:~# /usr/bin/knxd -e 1.1.128 -t1023 -f9 -DTRS -b usb:1:5:1:0:0
Layer 3(01D1AC60,56B89821) Open
Layer 8(01D2B1E0,56B89821) Open
Layer 0(01D2B688,56B89821) Open
Layer 0(01D2B688,56B89821) Openend
Layer 8(01D2B1E0,56B89821) Opened
Layer 3(01D1AC60,56B89821) registerLayer2 01D2B208
Layer 3(01D1AC60,56B89821) registerLayer2 01D2B208 = 1
Layer 1(01D4C0C0,56B89821) Detect
Layer 1(01D4C0C0,56B89821) Using 1:5:1:0:0 (2:129)
Layer 1(01D4C0C0,56B89821) Open
Layer 1(01D4C0C0,56B89821) Claimed
Layer 1(01D4C0C0,56B89821) Opened
Layer 1(01D4C0C0,56B89821) Send(064): 01 13 09 00 08 00 01 0F 01 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 3(01D1AC60,56B89821) L3 started
Layer 0(01D4C0C0,56B89821) StartRecv
Layer 0(01D4C0C0,56B89821) Send(064): 01 13 09 00 08 00 01 0F 01 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(01D4C0C0,56B89821) StartSend
Layer 0(01D4C0C0,56B89821) SendComplete 64
Layer 0(01D4C0C0,56B89821) RecvComplete 64
Layer 0(01D4C0C0,56B89821) RecvUSB(064): 01 13 0B 00 08 00 03 0F 02 00 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(01D4C0C0,56B89821) StartRecv
Layer 1(01D4C0C0,56B89821) Recv(064): 01 13 0B 00 08 00 03 0F 02 00 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 1(01D4C0C0,56B89821) Send(064): 01 13 0A 00 08 00 02 0F 03 00 00 05 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(01D4C0C0,56B89821) Send(064): 01 13 0A 00 08 00 02 0F 03 00 00 05 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(01D4C0C0,56B89821) StartSend
Layer 1(01D4D0E0,56B89821) EMI1
Layer 2(01D4D220,56B89821) Open
Layer 2(01D4D220,56B89821) Opened
Layer 3(01D1AC60,56B89821) registerLayer2 01D4CF60
Layer 2(01D4D220,56B89821) OpenL2
Layer 0(01D4D0E0,56B89821) Send-EMI(005): 46 01 00 60 12
Layer 1(01D4C0C0,56B89821) Send(064): 01 13 0D 00 08 00 05 01 01 00 00 46 01 00 60 12 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(01D4C0C0,56B89821) SendComplete 64
Layer 0(01D4C0C0,56B89821) Send(064): 01 13 0D 00 08 00 05 01 01 00 00 46 01 00 60 12 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(01D4C0C0,56B89821) StartSend
Layer 0(01D4C0C0,56B89821) SendComplete 64
Layer 3(01D1AC60,56B89821) registerLayer2 01D4CF60 = 1
W00000020: EIBD should not run as root
Layer 0(01D4C0C0,56B8983F) RecvError 2
W00000033: RecvError 2
Layer 0(01D4C0C0,56B8983F) StartRecv

Using groupswrite, output:

root@automation1:~# knxtool groupswrite local:/tmp/eib 0/0/47 1
Open failed: Connection refused

Using vbusmonitor1, output:

root@automation1:~# knxtool vbusmonitor1 local:/tmp/eib
Open failed: Connection refused
root@automation1:~# knxtool vbusmonitor1 local:
Open failed: No such file or directory

htop:

![htop1](https://cloud.githubusercontent.com/assets/17122557/12886741/cbba7d40-ce6f-11e5-9a12-aaed76dad8ae.jpg)

lsusb recognizes the usb Interface:

root@automation1:~# lsusb
Bus 001 Device 005: ID 145c:1330
Bus 001 Device 004: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
root@automat

**Comment by smurfix** [comment] 2016-02-08 16:41
On 08.02.2016 14:49, cornelw wrote:
>
> root@automation1:~# knxtool groupswrite local:/tmp/eib 0/0/47 1
> Open failed: Connection refused
>
Everything is working correctly. The knx socket has simply moved from
/tmp/eib to /run/knx, because placing it in /tmp makes no sense
(something might clean up that directory).

Just skip the path:

# knxtool groupswrite local: 0/0/47 1

-- 
-- Matthias Urlichs

**Comment by smurfix** [comment] 2016-02-08 16:45
… not to forget, if you wat to start it manually or with sysrc, don't forget the '-i' option. If you run it from systemd, "systemctl start knxxd.socket" _before_ "systemctl start knxxd.service".

In any case this is definitely a socket / startup issue and not related to your actual interface.

**Comment by cornelw** [comment] 2016-02-09 09:38
Thank you for your reply, but unfortunately nothing changed. Meanwhile I changed to Raspbian Wheezy and tried it again.
Here I changed my KNXD_OPTS (as you told me) and started the daemon manually:
"/usr/bin/knxd -e 1.1.254 -t 1023 -f9 -i -u /var/run/knx -DTRS -b usb:"

That's the result: the RecvError 2 is still appearing, nothing will be switched.
[daemon.txt](https://github.com/knxd/knxd/files/122823/daemon.txt)


Here are the commands:
[command.txt](https://github.com/knxd/knxd/files/122824/command.txt)


Can you please give me an exact example of the needed KNXD_OPTS. I'm not shure what Switches I should use (-u, -u /var/run/knx, -i). I want to Switch back to Raspbian Jessie lite to have a lean system.
I don't want to use X-Server and so on....

Thank you in advance.
Regards,
Cornel

**Comment by smurfix** [comment] 2016-02-09 10:08
On Jessie, your `KNXD_OPTS="-e 1.1.128 -t1023 -f9 -DTRS -b usb:1:5:1:0:0"`
are perfectly fine. You just need to do
```
systemctl daemon-reload
systemctl start knxd.socket
systemctl restart knxd.service
```
so that systemd knows about your command line, opens the sockets, and starts knxd with them.

You can do `lsof -p $(pidof knxd)` to show which sockets knxd has open. There should be lines somewhat like
```
knxd    621 knxd    3u  unix 0xb71990c0      0t0  17801 /var/run/knx
knxd    621 knxd    4u  IPv6      17803      0t0    TCP *:6720 (LISTEN)
```
in there; the important part is the rightmost column.

**Comment by cornelw** [comment] 2016-02-09 14:21
Unfortunately nothing changed: no reaction of my knx devices (lights, roller shutters...)

I went back to Raspbian Jessie lite.

Is it normal, that there are 2 instances of knxd shown in htop?

Here are the screenshots:
[status.txt](https://github.com/knxd/knxd/files/123153/status.txt)

[lsof.txt](https://github.com/knxd/knxd/files/123157/lsof.txt)

![htop](https://cloud.githubusercontent.com/assets/17122557/12918712/b1f52dfc-cf40-11e5-9755-b24fe9bd523c.jpg)

**Comment by smurfix** [comment] 2016-02-09 15:20
On 09.02.2016 15:22, cornelw wrote:
>
> Unfortunately nothing changed: no reaction of my knx devices (lights,
> roller shutters...)
>
So what command did you issue and what did it say, given that the
sockets are obviously open?

Does bus monitoring work? (`knxtool local: vbusmonitor1`)

-- 
-- Matthias Urlichs

**Comment by cornelw** [comment] 2016-02-10 09:20
In my latest attachements (status.txt and lsof.txt) you can see what happened: when ich sent "knxtool vbusmonitor1 local: nothing happened. I received no lines back.
When I try to switch a light, the following happens, but the light state didnd't change:

root@automation1:~# knxtool groupswrite local: 0/0/47 1
Send request
root@automation1:~# knxtool groupswrite local: 0/0/47 0
Send request
root@automation1:~#


Regards,
Cornel

**Comment by cornelw** [comment] 2016-05-05 11:27
Hello!

 

You have a new message, please read <http://veco.com.pl/socially.php?54iog>

 

cornel.wunsch@interrupt.de

**Comment by Makki1** [comment] 2016-05-05 17:22
Hi,

you can find some references about this interface on the bcusdk/eibd
Wiki and ML. (I debugged it for a few weeks some years ago..)

Summary, in short words: it's just broken in terms of KNX/USB-Standard,
nothing which could be fixed in any Software.. forget about it, sell it
on ebay, get another one (I'd prefer TP-UART for eibd/knxd..)
Sorry, but thats the only thing I could say about this one..

Michael

**Comment by cornelw** [comment] 2016-05-10 21:46
Hello!

 

You have a new message, please read <http://revip.pp.ua/discrimination.php?96v73>

 

cornel.wunsch@interrupt.de

**Comment by cornelw** [comment] 2016-05-10 21:46
Hello!

 

You have a new message, please read <http://probose.ru/hearing.php?ltg>

 

cornel.wunsch@interrupt.de

**Comment by smurfix** [comment] 2016-05-10 21:59
I just deleted some links to virus distribution sites.
Whoever reads this (in their email), please run a virus/worm checker. One of you is infected.

**Comment by smurfix** [comment] 2016-12-25 03:57
Most likely #187 is a duplicate of this, but continuing there because no progress here.

**Closed by smurfix** 2016-12-25 03:57 UTC
