### ISSUE TITLE
configure.ac:31: error: required file './ltmain.sh' not found

### ISSUE THREAD

**Issue by dtk33d** [knxd/knxd#474] opened 2020-05-05 09:48 UTC
Hello,

tried to compile on raspberry 3 with debian stretch:
```
git checkout deb

dpkg-buildpackage -b -uc

dpkg-buildpackage: info: source package knxd
dpkg-buildpackage: info: source version 0.14.35-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Matthias Urlichs <matthias@urlichs.de>
dpkg-buildpackage: info: host architecture armhf
 dpkg-source --before-build knxd
 debian/rules clean
dh clean
   dh_testdir
   dh_auto_clean
   dh_autoreconf_clean
        rm -f -- ./missing ./compile ./config.sub ./configure ./autom4te.cache/output.2 ./autom4te.cache/traces.1 ./autom4te.cache/traces.0 ./autom4te.cache/output.0 ./autom4te.cache/requests ./autom4te.cache/output.1 ./autom4te.cache/traces.2 ./config.guess ./m4/lt\~obsolete.m4 ./m4/ltversion.m4 ./m4/ltoptions.m4 ./m4/libtool.m4 ./m4/ltsugar.m4 ./depcomp ./config.h.in ./aclocal.m4 ./install-sh
        rm -f debian/autoreconf.before debian/autoreconf.after
        rm -f debian/*.debhelper.log
   debian/rules override_dh_clean
make[1]: Entering directory '/home/pi/knxd'
dh_clean
        rm -f debian/debhelper-build-stamp
        rm -f debian/knxd.substvars
        rm -f debian/knxd.*.debhelper
        rm -rf debian/knxd/
        rm -f debian/knxd-tools.substvars
        rm -f debian/knxd-tools.*.debhelper
        rm -rf debian/knxd-tools/
        rm -f debian/knxd-dev.substvars
        rm -f debian/knxd-dev.*.debhelper
        rm -rf debian/knxd-dev/
        rm -rf debian/.debhelper/
        rm -f debian/*.debhelper.log
        rm -f debian/files
        find .  \( \( \
                \( -path .\*/.git -o -path .\*/.svn -o -path .\*/.bzr -o -path .\*/.hg -o -path .\*/CVS \) -prune -o -type f -a \
                \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
                 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
                 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
                 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
                \) -exec rm -f {} + \) -o \
                \( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \)
        rm -f *-stamp
rm -f debian/knxd.install
make[1]: Leaving directory '/home/pi/knxd'
 debian/rules build
dh build
   dh_testdir
   dh_update_autotools_config
   dh_autoreconf
        find ! -ipath "./debian/*" -a ! \( -path '*/.git/*' -o -path '*/.hg/*' -o -path '*/.bzr/*' -o -path '*/.svn/*' -o -path '*/CVS/*' \) -a  -type f -exec md5sum {} + > debian/autoreconf.before
        autoreconf -f -i
libtoolize: putting auxiliary files in '..'.
libtoolize: copying file '../ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:31: installing './compile'
configure.ac:31: installing './config.guess'
configure.ac:31: installing './config.sub'
configure.ac:30: installing './install-sh'
configure.ac:31: error: required file './ltmain.sh' not found
configure.ac:30: installing './missing'
src/backend/Makefile.am: installing './depcomp'
autoreconf: automake failed with exit status: 1
        find ! -ipath "./debian/*" -a ! \( -path '*/.git/*' -o -path '*/.hg/*' -o -path '*/.bzr/*' -o -path '*/.svn/*' -o -path '*/CVS/*' \) -a  -type f -exec md5sum {} + > debian/autoreconf.after
dh_autoreconf: autoreconf -f -i returned exit code 1
debian/rules:14: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

**Comment by EricReiche** [comment] 2020-05-10 11:14
See #343
As a workaround, run `libtoolize` and try again.
This should still be fixed in the build script OR added to the readme.

**Comment by smurfix** [comment] 2020-05-10 13:18
Something more interesting is happening here since libtoolize *is* running, obviously.

**Comment by EricReiche** [comment] 2020-05-10 19:54
I found this issue here after googling because I had the same issue. Googling the error message lead me towards stackoverflow suggesting to run libtoolize (for a different tool/project), which worked for me.

**Comment by dallmair** [comment] 2024-12-31 00:07
Current situation:

This has been reported on Debian Stretch, which predates current stable (Bookworm) by a whopping 3 releases (Bullseye, Buster, Stretch). It affects the build toolchain, which has advanced since then, so it *might* have been fixed in the meantime. Independent of whether it has been fixed or not, it clearly affected or affects numerous other projects as well. So knxd *might* somehow inadvertently trigger this in unknown situations, but it's unclear when and how and why, and would take an inordinate amount of time to reproduce and analyze.

At the same time, there is an easy workaround available for everyone who might still trip into this: Run `libtoolize` manually, once, and try again. Not the best user experience, but at least doable. Plus, what I've found so far regarding this seems to imply it's related to some old cached files not being cleaned up, so a simple `git clean -fdx` might do the trick as well. Or, wipe your local clone of knxd and start fresh.

With the new CI on GitHub Actions, we can at least be sure it is not a code issue per se.

Taking all of this into account, I think it's better to close this issue for now. Please reopen if you find it's still an issue. In this case, please also add some information about your system and clone (upgraded? newly created? possibly accumulated cruft?).

**Closed by dallmair** 2024-12-31 00:07 UTC
