### ISSUE TITLE
Device programming ETS5 doesn't work all times

### ISSUE THREAD

**Issue by p3root** [knxd/knxd#121] opened 2016-02-02 08:39 UTC
Hey there!

I have some troubles with 2 KNX devices which cannot be programmed with knxd ethernet bridge and ETS5. 

I could program the physical address but not the application program (device not responding).

The devices are 2 shutter actuator (ABB JA/S4.6.1, ABB JA/S4.230.1). I have no problems with other devices as far. Maybe cause those devices use an extended knx programming interface or something similar?

What traces are needed to find this issue and fix it? Just give me a answer and I'll post the traces.

THANKS,
Patrik

**Comment by smurfix** [comment] 2016-02-05 11:40
What hardware interface + knxd command line are you using?

**Comment by p3root** [comment] 2016-02-10 12:29
I use a KNX EIB TP-UART2 from Siemens which uses to normal serial communication protocol.

I call the knxd with following command:

`/usr/bin/knxd --eibaddr=1.1.240 --GroupCache --listen-local=/var/run/eibd.42607.sock --pid-file=/var/run/eibd.42607.pid --tpuarts-disch-reset --tpuarts-ack-all-group tpuarts:/dev/ttyO1 19200`

**Comment by pfisterer** [comment] 2016-04-07 16:13
I have the same issue using a TPUART gateway (http://busware.de/tiki-index.php?page=TUL) and ETS5. It starts to program and then fails at approx. 20%.

**Comment by eghetto** [comment] 2016-05-13 19:19
Confirmed here! Using the same hardware as @pfisterer. Sometimes it helps to program physical address first, then the application following. BTW: Same issues with ETS4... Glad to deliver more input if required!

**Comment by smurfix** [comment] 2016-05-14 09:23
Ideally you'd use a second tpuart in busmonitor mode, to compare the programming attempt through knxd with a gateway that works. Obviously something is different.

Alternately you could log some traces on the IP network side and check what happens. Maybe it's just an issue of lost packets not getting repeated, or something along these lines.

**Comment by eghetto** [comment] 2016-05-14 10:46
Please find attached the wireshark capture files a well as the ets monitor file. One wireshark log file contains a successful attempt, the other the failed attempt. However, both look good to me... ETS' last monitor file entry just states: "T_Disconnect". That's all. ETS Activity Tab: "Device is not responding."

Please let me know if you'd like me to provide you with more details!

[knxd_ets_failure.zip](https://github.com/knxd/knxd/files/264473/knxd_ets_failure.zip)

**Comment by RedTiger26** [comment] 2016-08-01 19:32
I do have the same issue, no device programming possible in ETS5 via knxd.

I use an ABB IPS/S3.1.1 IP-Interface, 
my knxd options are: KNXD_OPTS="-e 2.1.1 --GroupCache --Discovery --Tunnelling --Server -b ipt:192.168.178.24"

I noticed that when I start the group monitor in ETS5, the source address column always shows "0.0.0" when I try to program devices through knxd. When I connect directly to the ABB IPS, the source address is the physical address of the device. For me, it looks like knxd does not use the correct source address in its frames.

**Comment by smurfix** [comment] 2016-08-02 05:08
On 01.08.2016 21:32, RedTiger26 wrote:
>
> I do have the same issue, no device programming possible in ETS5 via knxd.
>
> I use an ABB IPS/S3.1.1 IP-Interface,
> my knxd options are: KNXD_OPTS="-e 2.1.1 --GroupCache --Discovery
> --Tunnelling --Server -b ipt:192.168.178.24"
>
> I noticed that when I start the group monitor in ETS5, the source
> address column always shows "0.0.0" when I try to program devices
> through knxd. When I connect directly to the ABB IPS, the source
> address is the physical address of the device. For me, it looks like
> knxd does not use the correct source address in its frames.
>
Please check whether this is fixed in the conn_sep branch.


-- 
-- Matthias Urlichs

**Comment by RedTiger26** [comment] 2016-08-02 07:02
Is it safe to install both branches on the same system? (Using RPi 2). Or should I do a fresh install on a different SD card with the conn_sep branch?

**Comment by smurfix** [comment] 2016-08-02 07:33
On 02.08.2016 09:02, RedTiger26 wrote:
>
> Is it safe to install both branches on the same system? (Using RPi 2).
> Or should I do a fresh install on a different SD card with the
> conn_sep branch?
>
Simply rename the daemon, or sonething like that. The rest of the code
hasn't changed.

-- 
-- Matthias Urlichs

**Comment by stmichaelis** [comment] 2016-08-03 13:16
I have the same problem using a Raspberry 2 and the Pigator module from busware (I assume this is based on the same hardware as the module used by @pfisterer). Programming of some devices (MDT actuators) works roughly 50% of the time, some (MDT presence) completely fail.

I tried switching to the conn_sep branch as proposed by @smurfix, but knxd fails on the first connection attempt by ETS:
`knxd: queue.h:110: const T& Queue<T>::top() const [with T = Array<unsigned char>]: Assertion 'akt != 0' failed.`

My knxd commandline is: ` knxd -e 1.1.255 -E 1.1.21:10 -D -T -R -S -b tpuarts:/dev/ttyAMA0`, same as for the 0.10 branch without the `-E` option. I also tried all the tpuart-Ack-Options for the 0.10 version. Strange (?) behaviour in the ETS while programming is that the green progress bar jumps back a bit during the operation, what does not happen for devices which work (MDT weather station, Jung sensors).

**Comment by stmichaelis** [comment] 2016-08-10 06:45
Found a commit in the conn_sep-branch which seems to work for me: [https://github.com/knxd/knxd/commit/189b85161446bd22729133a5da853233436a3b5e](https://github.com/knxd/knxd/commit/189b85161446bd22729133a5da853233436a3b5e)

Still testing if this enables programming of all devices and bisecting when the assertion is triggered.

**Comment by smurfix** [comment] 2016-08-21 22:21
Any progress bisecting? The commit in question can't be responsible. :-P

**Comment by stmichaelis** [comment] 2016-08-23 20:26
No definite results yet. I can confirm that the commit I mentioned (which is rather old) let me program all devices I own. A different problem is that with this version sometimes the connection to knxd itself dies, but this happens rarely and does not completely prevent me from programming.

I got stuck during bisecting with quite a few steps which did not compile at all or segfaulted directly when run. But this may not be a problem of the code itself but rather of me simply compiling with make and replacing the knxd binary only. Also it seems that make clean sometimes still leaves artifacts behind preventing a fresh compile. I will need to find the time for a proper build-install-cycle per step.

**Comment by smurfix** [comment] 2016-08-23 21:07
Yes, that's a known problem. You need to always to a complete clean-out, ```nake clean``` should suffice, but you might want to be extra safe by running something like ```git ls-files --others -z | xargs -0 rm```.

**Comment by pfisterer** [comment] 2016-10-05 11:14
Any news on this issue? Can I support somehow in tracking down this issue?

**Comment by stmichaelis** [comment] 2016-10-11 16:58
Finally found some time for more tests, also thanks to @smurfix hints on cleaning up each build.
Current workaround: Commit ad2aa7b86ec45e1800ce21ccbcca30a7406c9087 seems to reliably work for me (still needs to stand test of time). Maybe @pfisterer can give this a shot as well? Please be aware that the knxd service was masked in this version for me, so a `sudo systemctl unmask knxd.service` may be necessary for testing.

## Details
### 0.10
Bisecting (see attached log [bisect_v0_10.txt](https://github.com/knxd/knxd/files/522421/bisect_v0_10.txt)) shows revision dcbbbd334342ae6279569260a2e68c4034a4ad05 to be the first non-working version. I understand that this exact commit targets the Raspberry Pi and should fix sending acks before the message was completely received, but appears to trigger timeouts in some cases. Unfortunately, my lack of understanding of the knx packets and protocol prevents seeing an obvious issue.

### 0.11
I could not make this branch (now master, formerly conn_sep) work for me to see if the same problem persists. Bisecting (see 
[bisect2_v0_11.txt](https://github.com/knxd/knxd/files/522425/bisect2_v0_11.txt)) leaves 31 non-buildable commits (seg faults, failed tests) as the reason for the triggered assertion. 
Maybe I should restart without the tests in the full build and can than in some cases at least get a runnable demon. My guess is, that the problem persists as the if clause is found there as well.

**Comment by pfisterer** [comment] 2016-10-26 06:24
Thank you @stmichaelis for sorting this out. For me, the build fails with the following message after running ```dpkg-buildpackage -b -uc```:

```
[...]
make[4]: Leaving directory '/root/knx-test/knxd/systemd'
make[3]: Leaving directory '/root/knx-test/knxd/systemd'
make[2]: Leaving directory '/root/knx-test/knxd'
make[1]: Leaving directory '/root/knx-test/knxd'
   dh_install
        install -d debian/knxd///usr/bin
        cp -a debian/tmp//usr/bin/knxd debian/knxd///usr/bin/
dh_install: knxd missing files (/lib/*), aborting
debian/rules:14: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: debian/rules binary gave error exit status 2
```
Any ideas?

**Comment by pfisterer** [comment] 2016-11-03 11:46
Removing ```/lib/*``` from ```debian/knxd.install.systemd``` solved the issue. Now, knxd is running. I'll test if programming works (probably) tonight.

**Comment by pfisterer** [comment] 2016-11-04 08:14
@smurfix I can confirm that programming works with the version mentioned by @stmichaelis. I'm using ETS 5.5.2 (Build 665).

**Comment by stmichaelis** [comment] 2016-11-06 20:07
Good to hear. Maybe the author of the original pull request @jsauermann is still active and can give a bit more details on why the patch was necessary. A solution working for all types of devices would be great. The if clause in questions dates back quite a long time to the original author of eibd: https://sourceforge.net/p/bcusdk/code/ci/b02c49bd49fe84e55c698ef61fdc43c074bd205c/

**Comment by jsauermann** [comment] 2016-11-06 21:35
Hi,
      
      I can try but I can't see or remember what the pull request was
      about.
      
      /// Jürgen
      
    
    On 11/06/2016 09:07 PM, Stefan
      Michaelis wrote:
    
    
      Good to hear. Maybe the author of the original pull request @jsauermann is still active and can
        give a bit more details on why the patch was necessary. A
        solution working for all types of devices would be great. The if
        clause in questions dates back quite a long time to the original
        author of eibd: https://sourceforge.net/p/bcusdk/code/ci/b02c49bd49fe84e55c698ef61fdc43c074bd205c/
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/knxd/knxd","title":"knxd/knxd","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/knxd/knxd"}},"updates":{"snippets":[{"icon":"PERSON","message":"@stmichaelis in #121: Good to hear. Maybe the author of the original pull request @jsauermann is still active and can give a bit more details on why the patch was necessary. A solution working for all types of devices would be great. The if clause in questions dates back quite a long time to the original author of eibd: https://sourceforge.net/p/bcusdk/code/ci/b02c49bd49fe84e55c698ef61fdc43c074bd205c/"}],"action":{"name":"View Issue","url":"https://github.com/knxd/knxd/issues/121#issuecomment-258706734"}}}

**Comment by jsauermann** [comment] 2016-11-07 17:50
Hi,

I only vaguely remember what the matter was. I believe it was about checking
in[5] is only valid if in() is long enough (so that in[5] is actually 
valid and not, for
example, from the previous telegram).

But I don't remember if that was my fault or somebody else's. At that 
time I was chasing
a problem that the ACK was apparently sent too late for the ELMOS UART 
and caused
each telegram to be repeated 3 times. However, somewhat later we figured 
that the delay
was caused by the operating system and maybe not by the code in eibd.

Anyhow, if you double check that single line of code and find it 
correct, then everything
should be OK.

/// Jürgen

**Comment by pfisterer** [comment] 2016-11-08 15:53
Thank you! How do we proceed to close this issue? @stmichaelis, could you prepare a pull request for @smurfix?

**Comment by smurfix** [comment] 2016-11-08 17:42
Hmm. I just straced it here.

```
read(11, "\x9c\x11\x64\x10\x40\xe5\x00\x80", 255) = 8
read(11, "\x3e\xcc\x49\xba\x22", 255)   = 5
```
So there are 8 bytes plus the length from the sixth byte, which looks right. However, if the problem is that the ack needs to be sent a bit early, then 7+… instead of 8+… should work. I'll test.

**Comment by stmichaelis** [comment] 2016-11-08 17:52
Found a bit of the specification online. Therefore the length field in byte `in[5]` is `len(payload)-1`, i.e. starts at 0 even as the minimum payload is one byte.
From the point of view of complete packet reception the if clause should be correct, nevertheless seems to trigger timing problems.
Depending on your @smurfix findings I would suggest to revert the patch to the original `in() < 6` as it a) appears to not be the cause of @jsauermann 's original problem and b) seems to trigger timeouts for some devices.
From a logical point of view I am confused: If the packet is not completely received you cannot validate the checksum and an early ACK should not make sense. Despite of this, the early ACK seems to have worked for years.

**Comment by jsauermann** [comment] 2016-11-09 10:42
Hi.

as far as sending the ACK too early seems to be no problem, at least for 
some UARTS.

If I remember correctly then we contacted the manufacturer of the ELMOS 
chip regarding
this question and got the answer that the ELMOS would not sent the ACK 
onto the KNX bus
if the received checksum turned out to be wrong after having AKed the 
ongoing telegram.

/// Jürgen

**Comment by smurfix** [comment] 2016-11-09 12:01
> Found a bit of the specification online.
URL please.

**Comment by do13** [comment] 2016-11-09 12:05
The KNX specification can be obtained at the KNX shop, free of charge, only
registration needed.

https://my.knx.org/de/shop/knx-specifications

2016-11-09 13:01 GMT+01:00 Matthias Urlichs <notifications@github.com>:

**Comment by stmichaelis** [comment] 2016-11-23 21:17
Opinions from the maintainers on how to proceed? I could create a pull request for going back to the original if clause.
I also identified the line where the assertion for the 0.11 version is triggered. Opened #166 for this as the problem seems independent.

For sake of completeness: I found the spec of the packet in this thesis: https://www.praus.at/files/diplomarbeit_fpraus_printed.pdf on page 26. But the hint on the original spec as indicated by @do13 should be better.

**Comment by smurfix** [comment] 2016-11-23 22:07
OK. please prepare a pull request.

**Comment by pfisterer** [comment] 2016-12-08 16:02
@stmichaelis Did this work for you? I did some quick testing and programming did not work for me after applying the pull request. I tried this on a Raspberry Pi 2 and a Gigabyte Brix w/o success.

**Comment by stmichaelis** [comment] 2016-12-08 19:35
Yes, appears to work for me as good as the identified good commit, at least so far while tinkering. Did you patch this into the *stable* branch? Master never worked for me, with or without the patch.
Alternatively, you could check out the stable branch of the fork i created for the pull request.
I did a clean dpkg -r, build and dpkg -i before testing.

**Comment by smurfix** [comment] 2016-12-25 04:11
Fixed in 524875a

**Comment by senselessDev** [comment] 2016-12-30 16:04
@smurfix You fixed it in the master branch, but if i understood @stmichaelis correct, the master branch is not working for him anyhow. Will it be merged into the stable branch as well?

**Comment by stmichaelis** [comment] 2017-01-08 20:49
@senselessDev You should try the patch with the current stable version and see if this fixes the problem for you. The commit I found working (https://github.com/knxd/knxd/commit/ad2aa7b86ec45e1800ce21ccbcca30a7406c9087) is rather old and I only used it to program all devices. I suggest you apply the fix manually (it is just uncommenting one line and commenting another) or temporarily check out the fork I created to test this: https://github.com/stmichaelis/knxd/tree/stable. Please be aware that by now my fork may be a few commits behind origin stable. I did not update since then as knxd is running rock solid for all devices.

**Comment by smurfix** [comment] 2017-01-11 19:44
Please test the libev version. I have successfully exercised ETS5 programming with usb:, tpuarts: and ipt: back-ends.

**Closed** 2017-01-19 15:54 UTC

**Comment by pfisterer** [comment] 2017-01-19 16:35
Hi All, thank you very much for tracking down and fixing this bug!
