### ISSUE TITLE
Remove option to build without libstdc++

### ISSUE THREAD

**Issue by timowi** [knxd/knxd#23] opened 2015-01-08 22:38 UTC
currently there is an option to build without libstd++. I think this is legacy of bcusdk. Nowadays stdc++ is available on all our targeting platforms. Therefore this option and the code belonging to this should be removed.

If there is any good reason please speak up now.

**Comment by p3root** [comment] 2015-01-08 23:07
http://stackoverflow.com/questions/174449/to-stl-or-stl-that-is-the-question
A very interesting discussion.

**Comment by timowi** [comment] 2015-01-09 00:34
> http://stackoverflow.com/questions/174449/to-stl-or-stl-that-is-the-question
> A very interesting discussion.
I do not think discussions like that help. I do programming of controllers and really small systems form time to time. If you have no virtual memory or less that a few MB of RAM stdc++ is no option.
Knxd already make use of dynamic allocation and uses quite some memory. So stdc++ makes almost no difference here.

So there are only two points here
1. Systems with no or broken stdc++. Are there any relevant ones today?
2. space consumption for the executables/libraries. The question here is does stdc++ really matter here? How much is it especially in comparison to knxd size. Are there really relevant systems (with knxd installed) where no other application uses libstdc++?

**Comment by Makki1** [comment] 2015-01-09 18:37
I agree in discussing this, but please post release 1.0; There are indeed platforms without libstdc++ (or with uclibcxx) which should be considered. 
700kB can make a big difference, if you have 8MB Flash and 4MB available it's 25% ..

**Comment by timowi** [comment] 2015-01-09 19:00
> I agree in discussing this, but please post release 1.0; There are indeed platforms without libstdc++ (or > with uclibcxx) which should be considered. 
> 700kB can make a big difference, if you have 8MB Flash and 4MB available it's 25% ..

yes, you're right. But I do not think this is a good target for knxd. knxd itself takes some memory. 

If I remeber correctly, ulibc++ is far less than 100kb. 800kb is my normal libstdc++ with all features on a desktop linux.

If there are other programs which need stdc++ you need it anyway. In other cases we could try to link stdc++ static. Unneeded parts should be removed then and the additional memory usage should be minimal.

Maintaining our own basic functionality will be a hard job. These will most probably be slower than stdc++ implementation. std functions are quite good and well tested nowadays. And they are optimized on most platforms. Completely avoiding all features from stdc++ makes development more complicated.

**Comment by tru7** [comment] 2015-01-09 19:02
@timowi I am not a developper so I cannot argue on the question weather to use libstdc++ or not in the future. I'm focusing on OpenWrt, here size can be crucial when using your wifi router to put some useful software on it while it runs anyway.
@2: I'd prefer wifi routers not being dropped as plattform
Talking about size:
knxd package built with --without-libstdc: about 120kBytes
knxd package built with uClibc++ : about 130kBytes + about 65kBytes
So I guess it is not a very big deal
@1: I don't know if uClibc++ is broken or not, I never needed it. But my tests of today at least show a fine running knxd so far.

**Comment by RichiH** [comment] 2015-01-09 20:09
Maintaining libraries in tree, or even linking parts statically, is a great
way to stay out of Debian...

Richard

Sent by mobile; excuse my brevity.

**Comment by ChristianMayer** [comment] 2015-01-09 20:25
Am 09.01.2015 um 20:00 schrieb Timo:
> If there are other programs which need stdc++ you need it anyway. In
> other cases we could try to link stdc++ static. Unneeded parts should be
> removed then and the additional memory usage should be minimal.
> 
> Maintaining our own basic functionality will be a hard job. These will
> most probably be slower than stdc++ implementation. std functions are
> quite good and well tested nowadays. And they are optimized on most
> platforms. Completely avoiding all features from stdc++ makes
> development more complicated.

And isn't std::string header only anyway? (Not sure about that, though)

I also fully agree that routers should be / stay supported.
But that's usually not achieved by duplicating code - it's normally
helpful to go to mainstream implementations that are already available
on the system.

As eibd used it's own, home brewn string class it really makes sense to
replace it by a standard implementation. (BTW: looking at my_strings.h I
can see quite a few security concerns that the usual implementations
should't have anymore)
But here I also agree that this isn't a top priority issue - and thus
the current coding should stick with the current solutions.

CU,
Chris

**Comment by timowi** [comment] 2015-01-09 21:17
> Maintaining libraries in tree, or even linking parts statically, is a great
> way to stay out of Debian...

Doing this as an option have no impact on debian. Were just talking about a replacement for --without-stdc++ option. By the way embed building and static linking of pthsem (as an option of course) is the only possible way I see to get into debian as long as we do not move away from pthsem...

> I also fully agree that routers should be / stay supported.

It's not about supporting router (or in general small and exotic systems). It's only about not supporting systems which can not afford the extra 75KB of stdc++ linking. I think knxd will grew anyway in future. Systems where you have to count every byte should not be considered too much. And the own implementations take some space too.

> (BTW: looking at my_strings.h I
> can see quite a few security concerns that the usual implementations
> should't have anymore)
yeah, it's a bit scaring. Second it misses a lot of helpful features. And third it is inefficient. stdc++ is well optimized on almost all platforms. Not talking about many possible bugs because new code may use it slightly different than old one.

> But here I also agree that this isn't a top priority issue - and thus
> the current coding should stick with the current solutions.
It's just the other way round: For new development it's easier to simply use c++ features instead of limiting to c and the own implementations. I have to look regularly in the String and Array class to find out what is possible and how it could be used. The functionality is limited.

So the real question is do we want to put the effort in avoiding standard c++ features just to support this really small set of systems? One more time: We are talking about just 75KB code size. You will need more the 100KB for knxd anyway. So how much systems are affected by this?

**Comment by p3root** [comment] 2015-01-09 22:33
I think in times of Rasperry PIs, where you could effort one for only 30€. You could let your router be as it is designed for and replace it with a Rasperry and let him work on the knx bus.

I think stl is a must. When you start new C++ projects you think about useing other frameworks like boost or Qt, which needs a lot more memory and space consumption.

If we discuss useing stl or not, we also can discuss of replacing pth.

________________________________
Von: Timo<mailto:notifications@github.com>
Gesendet: ‎09.‎01.‎2015 22:17
An: Makki1/knxd<mailto:knxd@noreply.github.com>
Cc: Patrik Pfaffenbauer<mailto:patrik.pfaffenbauer@p3.co.at>
Betreff: Re: [knxd] Remove option to build without libstdc++ (#23)

> Maintaining libraries in tree, or even linking parts statically, is a great
> way to stay out of Debian...

Doing this as an option have no impact on debian. Were just talking about a replacement for --without-stdc++ option. By the way embed building and static linking of pthsem (as an option of course) is the only possible way I see to get into debian as long as we do not move away from pthsem...

> I also fully agree that routers should be / stay supported.

It's not about supporting router (or in general small and exotic systems). It's only about not supporting systems which can not afford the extra 75KB of stdc++ linking. I think knxd will grew anyway in future. Systems where you have to count every byte should not be considered too much. And the own implementations take some space too.

> (BTW: looking at my_strings.h I
> can see quite a few security concerns that the usual implementations
> should't have anymore)
yeah, it's a bit scaring. Second it misses a lot of helpful features. And third it is inefficient. stdc++ is well optimized on almost all platforms. Not talking about many possible bugs because new code may use it slightly different than old one.

> But here I also agree that this isn't a top priority issue - and thus
> the current coding should stick with the current solutions.
It's just the other way round: For new development it's easier to simply use c++ features instead of limiting to c and the own implementations. I have to look regularly in the String and Array class to find out what is possible and how it could be used. The functionality is limited.

So the real question is do we want to put the effort in avoiding standard c++ features just to support this really small set of systems? One more time: We are talking about just 75KB code size. You will need more the 100KB for knxd anyway. So how much systems are affected by this?




---

**Comment by J-N-K** [comment] 2015-01-10 07:22
@P3: I disagree. RPis are nice for testing, but not production. I own three of them, one accepts SD-cards only if they are hold in position with papersheets, another one has a similar problem with the power jack and the third one stopped working after seven or eight months. In addition they lack proper housing.
I have never seen that with small routers.

Regards,

Jan

**Comment by p3root** [comment] 2015-01-10 09:38
@J-N-K Raspberry was just an example. There are also other boards which are effortable.

**Comment by RichiH** [comment] 2015-01-10 10:09
As we are totally off-topic and deep into bikeshedding territory anyway:

* While early RasPis had some issues, the newer builds are pretty solid. You can get a myriad of cases for them. Point in case, I had a RasPi outside in heavy rain, storms, and sun for almost a year without any issues other than frequent power outages in the distribution running to the RasPi
* If you want serious hardware (for home, small offices, or in Alix' case industrial sites), look at Alix boards, Ubiquti, or RouterBoard
* It's "affordable", not "effortable" ;)
* All this chit-chat is neither suited for a forum nor for github; how about IRC? I openend '##smarthome` on `irc.freenode.net` in case anyone cares to join. It's a project-agnostic channel on purpose so topics like EnOcean etc could be discussed as well.

**Comment by Makki1** [comment] 2015-01-10 15:59
Well we are somewhat OT but not totally, as we discuss wether to bloat knxd for some reason like "another bloated HW with more core and more RAM is cheap enough" - which I won't underwrite! Means: I fully disagree in such an argumentation "this makes sense just because there is bigger HW available"
It is and should be up to the user to run knxd on a 180MHz MIPS or ARM with 4MB Flash/32 MB RAM or an Octacore i7

**Comment by Makki1** [comment] 2015-01-10 16:08
And to get back on-topic: there should be a solution to solve this while maintaining compatibility to very small systems AND make others (like Debian) happy.

P.S.: I also tend to "just integrate" pthsem - at least for now. Besides linknx I'm not aware of any other SW using it..

**Comment by ChristianMayer** [comment] 2015-01-10 17:42
I just had a look at the configure script of bcusdk 0.0.5 with regards to the  --with-libstdc. Actually, I have no clue what that will bring - it's only defining USE_NOLIBSTDC and that is only used in common/types.h where it will additionally include common/libstdc.h. And that will define a bit of memory handling.

So my conclusion (w/o testing anything) is that this flag creates no reason to link with the C++ standard library (which, btw, is the correct name. STL should not be used anymore to talk about the C++ standard lib - see http://www.parashift.com/c++-faq-lite/stl.html).

When that is true, a refactoring to use real strings (i.e. std::string) and arrays should *not* cause any binary bloat as those parts from stdlib are header only IIRC.

**Comment by p3root** [comment] 2015-01-12 07:55
@Makki1 Nevertheless KNX components are very expensive any way. So why should it not be possible to set our minimum requiremes a little bit higher? If we say we need (only estimated) about 2MB space size, than it is so. We could make it much easier for us to develop. Maybe we should start a new discussion about the min. requirements?

**Comment by timowi** [comment] 2015-01-12 12:02
@Makki1 I think your arguing is a bit overdrawn. We are not talking about bloating knxd here. Or it is blown anyway. Just how you look at it.

The fact about current situation:
 * Knxd needs a posix compatible operating system
 * Knxd uses a lot of dynamic memory (often quite small) different sizes.

Because of these two you need at least some MB of ram and a few MB flash. If you reprogram it with mostly static memory and without complete OS the same functionality could (mostly) run with a few KB of each. So the expensive requirements are already there.

Your example with 4MB Flash/32 MB RAM is no Problem either way. We are talking about 70KB flash for dynamic sdtc++ linking. Possible much less with static linking (unused code can be removed then). On the other side the duplicated code could be removed in future, so size will decrease a bit.

We are just talking about a fraction of the memory needed by knxd anyway. Completely avoiding stdc++ function will make development more complicated and more error prone. Where do you want to draw the line? We want to add more functionality. So code size will increase. (not to MB) but a few KB can not be avoided. Stop implementing features if we hit 200KB? Rip of logging and rare used features to stay below?

**Comment by Makki1** [comment] 2015-01-13 17:09
First of all: **with the given arguments, I agree this makes sense**

Second, I really want to explain, why I'm first skeptic in such questions:
I've seen too many projects in the last years being bloated just for the sake of "bigger, better, higher" or "latest & greatest".
This often starts with marking requirements which aren't really required like newest lib-versions, debhelper, ...
This has a simple reason: while we are used to a lifecycle of 2-4y for smartphones and desktops, I assume a lifecycle of 10++ years for smarthome/building-automation.

Finally, I think we should just have a look, if it might also works with uclibcxx (if possible) or - if not - explicit deny it (I'll test, hopefully tru/Othmar also)

**Comment by tru7** [comment] 2015-01-13 21:03
Personally I'll be happy to build and test the openwrt packages. Dealing with openwrt is my hobby and I have a KNX installation at home with an IP gateway, no USB nor TPUART though. I already build a version with and one without uclibcxx and both run fine so far.
I'd prefer if the size of knxd could stay small of course, so I can keep it on the wifi router platform. As I mentioned earlier it seems no big deal in size right now when using uclibcxx. I'm not opposing to use stdc++ and I think it's OK not to support duplicate code. I just hope size will always stay a criteria in development.
As a minimal goal for a final version 1.0 knxd should just stay basically the same as it is now, just with the needed patches and cleanups. So at least a version 1.0 could then provide a usable variant for openwrt.

**Comment by Makki1** [comment] 2015-01-13 21:26
Othmar, I support this change (after two days reading & testing..) but I would be very happy if you also report possible problems and test branches.

I think problems - if existing - could be solved if we work together. Also, duplicating code or "own" replacements for std-functions are bad by design.
I want to take care knxd stays small and lean, but in this case, I maybe was too strict. 
Anyway, it will stay small & lean.

USB-support on openwrt (or OE) is another issue beyond this.. KNX-USB if's are just broken anywhere at all IMHO, so I don't really care. (yes, support will stay, but not with a copy of an old libusb as it was..) and USB-TPUART is just serial, there are no issues or problems..

**Comment by tru7** [comment] 2015-01-13 22:00
@Makki1 regarding libusb on openwrt: I succesfully requested to go to libusb-1.0 1.0.19 which is now included in trunk since yesterday. I already build knxd with --enable-usb for openwrt. I just did not push the change to github yet because I wanted to wait for other merges on knxd.

**Comment by timowi** [comment] 2015-01-18 12:44
ok, lets avoid stdc++ for 1.0 release, but allow it later. without-stdc++ will be removed then and instead static-stdc++ option can be added for small systems.

**Comment by smurfix** [comment] 2016-12-19 00:14
The 1.0 release will use libev's c++ bindings. The work to remove the stdc++ dependency would be considerable and most likely not be useful. Thus I am closing this bug.

**Closed by smurfix** 2016-12-19 00:14 UTC
