### ISSUE TITLE
USB Resource unavailable

### ISSUE THREAD

**Issue by stargieg** [knxd/knxd#119] opened 2016-01-25 22:50 UTC
Hi
I have a Problem with Gira USB.
knxd run and works only in forground with --error=1

This works somtime

```
knxd --error=1 --listen-local=/var/run/knxd --pid-file=/var/run/knxd.pid --layer2=usb:2:2:1:0:0
knxtool groupswrite local:/var/run/knxd 0/0/1 0
```

but not with bash & or with --daemon. The result is a zombie process or an segfault

```
[ 2418.930045] usb 2-2: usbfs: interface 0 claimed by usbfs while 'knxd' sets config #1
[57294.535943] knxd[14862]: segfault at 8 ip b76ce62e sp 0847af34 error 6 in libuClibc-0.9.33.2.so[b769a000+4f000]
```

I have compile knxd with -g and -O0 for openwrt x86 with gdbserver and valgrind.
What is the preferred way to figure out what is going wrong?

`strace knxd --listen-local=/var/run/knxd --pid-file=/var/run/knxd.pid --layer2=usb:2:2:1:0:0`
https://gist.github.com/stargieg/092dd06f4f47cbf6aad4

**Comment by smurfix** [comment] 2016-12-25 04:24
Unfortunately I don't own any USB interfaces to test this with.

WRT the segfault: please start with gdb and post the backtrace.

valgrind is unuseable with knxd due to the pthsem library. This will be fixed in the libev branch which is not yet production ready.

**Comment by smurfix** [comment] 2017-01-19 16:34
The libev port is done and part of 0.12.
Please run knxd under gdbserver and generate a stack trace of the segfault, assuming that it is reproducible in 0.12.

**Comment by smurfix** [comment] 2017-01-30 17:08
Closing due to lack of feedback. Please re-open when appropriate.

**Closed by smurfix** 2017-01-30 17:08 UTC
Labels: waiting for feedback
