### ISSUE TITLE
progmodeon doesn't work

### ISSUE THREAD

**Issue by adibacco** [knxd/knxd#476] opened 2020-06-01 18:58 UTC
I tried the following command:

`pi@raspberrypi3:~ $ knxtool progmodeon ip: 0.0.8`
`Set failed: Connection reset by peer`

Also progmodestatus seems not to work.

**Comment by smurfix** [comment] 2020-06-02 05:03
That's right. knxd is now a KNX router. The code for connection-oriented programming is still present but disabled because it won't work with an event-based program without major refactoring, which I didn't do because that stuff should live in a separate program.

Also, duplicate of #256 so I'm closing this one.

**Closed by smurfix** 2020-06-02 05:03 UTC
