### ISSUE TITLE
Interface option in config ini seems to be ignored

### ISSUE THREAD

**Issue by ToGe3688** [knxd/knxd#492] opened 2020-12-04 12:16 UTC
When i try to run knxd it seems that the interface option is ignored. Knxd is starting fine and i can connect via ETS5 but only using the local network (eth0) and not via the configured interface nrtap. Am i missing something in my configuration or is this a bug?

Knxd Version: 0.14.30-1
Hardware: Raspberry Pi4

Here is my config ini

[A.cache]
debug = debug-A.cache
[B.ipt]
driver = ipt
ip-address = 192.168.178.58
[debug-A.cache]
trace-mask = 0x3ff
[debug-server]
name = mcast:knxd
[main]
addr = 15.15.250
cache = A.cache
client-addrs = 15.15.245:8
connections = B.ipt,server
systemd = systemd
[server]
debug = debug-server
discover = true
server = ets_router
tunnel = tunnel
interface = nrtap

Ip addr output:
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether dc:a6:32:6e:64:bc brd ff:ff:ff:ff:ff:ff
    inet 192.168.178.91/24 brd 192.168.178.255 scope global dynamic noprefixroute eth0
       valid_lft 845325sec preferred_lft 737325sec
3: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether dc:a6:32:6e:64:bd brd ff:ff:ff:ff:ff:ff
12: nrtap: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1300 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether d2:83:bb:e9:2b:7f brd ff:ff:ff:ff:ff:ff
    inet 192.168.168.2/24 brd 192.168.168.255 scope global nrtap
       valid_lft forever preferred_lft forever

**Comment by dallmair** [comment] 2024-11-17 12:56
This is a duplicate of #479.

**Unrelated note:** Your config has an issue with KNX addresses as your configured `addr` is in the span of `client-addrs` when it should be distinct.

**Closed by dallmair** 2024-11-17 12:56 UTC
