### ISSUE TITLE
Building error on Raspi with Jessie

### ISSUE THREAD

**Issue by onkelandy** [knxd/knxd#238] opened 2017-03-24 14:22 UTC
When I build the newest release I get the following error:
```
+ knxd -B log -e 1.2.3 --stop-right-now -b dummy: -b dummy:
+ knxd -e 1.2.3 --stop-right-now -b dummy: -b dummy: --tpuarts-disch-reset
+ echo 'Bad argument D'
Bad argument D
+ cat /tmp/filexg0wlb
+ exit 1
debian/rules:48: recipe for target 'override_dh_auto_test' failed
make[1]: *** [override_dh_auto_test] Error 1
make[1]: Leaving directory '/root/knxd'
debian/rules:14: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

After executing the command manually I get:
You provided L2 flags after specifying an L2 interface.

**Comment by chefkoch009** [comment] 2017-03-24 17:01
Hi,
I had the same problem. I commented out the block in the file tools/test.sh containing the 2 if-blocks  with "--tpuarts-disch-reset".
then it worked for me.

**Comment by onkelandy** [comment] 2017-03-24 19:18
Thanks, I've deleted the two parts and building was fine. However after installing I get this error:
```
The system user `knxd' already exists. Exiting.
Job for knxd.service failed. See 'systemctl status knxd.service' and 'journalctl -xn' for details.
Job for knxd.service failed. See 'systemctl status knxd.service' and 'journalctl -xn' for details.
invoke-rc.d: initscript knxd, action "restart" failed.
dpkg: error processing package knxd (--install):
 subprocess installed post-installation script returned error exit status 1
```

I guess it's just because it doesn't know where the ini-File is.. I get this log entry when I run journalctl -xn

```
-- Unit knxd.service has begun starting up.
Mär 24 20:11:14 smarthome knxd[17916]: Usage: knxd configfile [main-section]
Mär 24 20:11:14 smarthome systemd[1]: knxd.service: main process exited, code=exited, status=1/FAILURE
Mär 24 20:11:14 smarthome systemd[1]: Failed to start KNX Daemon.
-- Subject: Unit knxd.service has failed
```
I've read in the forum that you should write the path to the ini file in knxd.conf and the install script will create a link. Didn't happen. Creating the link by myself leads to the same error as above plus "Ignoring invalid environment 'ip-address=10.0.0.101': /etc/knxd.conf"

Changing the service file to "ExecStart=/usr/bin/knxd /etc/knxd.ini" gives me this error:
```
knxd: inifile.cpp:75: std::string& IniSection::operator[](const char*): Assertion `v != values.end()' failed.
```

Running knxd /etc/knxd.ini without the systemd service kind of works but not really. It's running but I can't use it. I've created the ini file via knxd_args. Looks like this:
```
[A.ipt]
driver = ipt
ip-address = 10.0.0.101
[main]
addr = 1.1.65
cache = B.cache
connections = A.ipt
systemd = systemd
```

**Comment by chefkoch009** [comment] 2017-03-24 19:27
I don't use the ini-file concept, because it's really new and i wait for a proper documentation. The way i gone is: keep it simple.
after installation leave all as it is. 
But there are 2 file: /etc/knxd.conf and /etc/default/knxd. I don't know at the moment which on is the right one, but you only need to edit the "args" line in the commandline style, but without -p and -u switch. As I see your generated config, your tag have a look next to:
`-e1.1.65 -E1.1.66:8 -DTRS -c -b ipt:10.0.0.101`

**Comment by smurfix** [comment] 2017-03-24 19:31
Of course you can't use it, you don't have any way to talk to it if you're not using systemd. You need the -u and/or -i options (resp. the equivalent ini-file entries, which boil down to changing the connections line to `connections=A.ipt,knxd_unix,knxd_tcp`in your case).

I'll investigate the crash; it'd help if you can give me a stack trace. systemd should have captured a core dump (see "man coredumpctl").

**Comment by onkelandy** [comment] 2017-03-24 19:35
Thanks for the quick answer. When I put the service file back to:
[Service]
EnvironmentFile=/etc/knxd.conf
ExecStart=/usr/bin/knxd $KNXD_OPTS

and just put this in both config files the same line as with 0.12:
KNXD_OPTS="-e 1.1.65 -i -b ipt:10.0.0.101 -c"

I still get the same inifile error?

**Comment by chefkoch009** [comment] 2017-03-24 19:37
@smurfix: how would look the config if i have 2NICs. NIC1 has ip and connection to KNX/GW and NIC2 has to provide the mcast to the net, where I work with ETS?

**Comment by onkelandy** [comment] 2017-03-24 19:40
Ok. Everything back to how it was. Service-File:
[Service]
EnvironmentFile=/etc/knxd.conf
ExecStart=/usr/bin/knxd $KNXD_OPTS

/etc/knxd.conf same as it was in 0.12:
KNXD_OPTS="-e 1.1.65 -i -b ipt:10.0.0.101 -c"

Deleted ini-File. Got same error as before:
knxd: inifile.cpp:75: std::string& IniSection::operator[](const char*): Assertion `v != values.end()' failed.

**Comment by onkelandy** [comment] 2017-03-24 19:46
With this ini File:
```
[A.ipt]
driver = ipt
ip-address = 10.0.0.101
[main]
addr = 1.1.65
client-addrs=1.1.66:8
connections=A.ipt,knxd_unix,knxd_tcp
systemd = systemd
```

I get a F00000000: [ 1:main] Error setting up the KNX router.

**Comment by smurfix** [comment] 2017-03-24 19:55
@chefkoch009 You can use an interface=ethX parameter in the ini file, or as the third parameter of ip:/-S=. (The first two atre the multicast address and port.) However it's been only lightly tested.

@onkelandy Right, that was a bug (the knxd_args verso. Please update to commit 1a85038 and try again.

**Comment by onkelandy** [comment] 2017-03-24 20:26
Thanks, I got one step closer.. Though the knxd_args still made one mistake. The ip-address got into the pace section, not in the ipt:
```
[B.ipt]
driver = ipt
filters = C.pace
[C.pace]
delay = 30
filter = pace
ip-address = 10.0.0.101
```
When I change the ip-address error it works when I start knxd /etc/knxd.ini
But how can I use the service? No matter how I try I always get either the info about the usage or the inifile error from above...

**Comment by smurfix** [comment] 2017-03-24 20:41
what command line did you use??

```
$ src/server/knxd_args -e 1.1.1 -B pace -b ipt:10.1.2.3
[A.ipt]
driver = ipt
filters = pace
ip-address = 10.1.2.3
[main]
addr = 1.1.1
connections = A.ipt
systemd = systemd
```

**Comment by onkelandy** [comment] 2017-03-24 20:46
this combination seems to be the problem:
-i --send-delay=30

**Comment by smurfix** [comment] 2017-03-25 08:45
No it's not.
Again, please tell me the **complete** command line that caused this.

**Comment by onkelandy** [comment] 2017-03-25 15:51
ok, looks like it is a matter of order.. this brings the false ini file. Without -E, without -B it's the same:
knxd_args -e 1.1.61 -E 1.1.62:8 -i --send-delay=30 -B single -b ipt:10.0.0.101 -c

still looking for a way to start it as a service though.. It only works from the command line directly.

**Comment by smurfix** [comment] 2017-03-25 16:14
Thanks, that does help fix the problem. I'll get to that.

In any case, what's the problem w/ starting via systemd? Just set KNXD_ARGS=/etc/knxd.ini (or whatever). If that doesn't work, add debugging options 
```
[main]
…
debug = debug-main
[debug-main]
error-level = 0x9
trace-mask = 0x3ff
```
start via systemd (don't forget to restart systemd.socket before systemd.service) and send me the output of `journalctl -u knxd -n100`.

**Comment by smurfix** [comment] 2017-03-25 16:19
Arguments are fixed in 2e21350

**Comment by onkelandy** [comment] 2017-03-25 16:58
This is weird. In the original service file it states
EnvironmentFile=/etc/knxd.conf
ExecStart=/usr/bin/knxd $KNXD_OPTS

So I put KNXD_OPTS=/etc/knxd.ini in the knxd.conf file
Works fine when I manually start with systemctl start knxd
Doesn't work if I want to start the service on startup by 
systemctl enable knxd

There I get:

```
Mär 25 17:43:49 smarthome systemd[1]: Starting KNX Daemon...
Mär 25 17:43:49 smarthome knxd[2146]: knxd: inifile.cpp:75: std::string& IniSection::operator[](const char*): Assertion `v != values.end()' failed.
Mär 25 17:43:49 smarthome systemd[1]: knxd.service: main process exited, code=killed, status=6/ABRT
Mär 25 17:43:49 smarthome systemd[1]: Failed to start KNX Daemon.
Mär 25 17:43:49 smarthome systemd[1]: Unit knxd.service entered failed state.
Mär 25 17:43:59 smarthome systemd[1]: knxd.service holdoff time over, scheduling restart.
Mär 25 17:43:59 smarthome systemd[1]: Stopping KNX Daemon...
Mär 25 17:43:59 smarthome systemd[1]: Starting KNX Daemon...
Mär 25 17:43:59 smarthome knxd[2152]: knxd: inifile.cpp:75: std::string& IniSection::operator[](const char*): Assertion `v != values.end()' failed.
Mär 25 17:43:59 smarthome systemd[1]: knxd.service: main process exited, code=killed, status=6/ABRT
Mär 25 17:43:59 smarthome systemd[1]: Failed to start KNX Daemon.
Mär 25 17:43:59 smarthome systemd[1]: Unit knxd.service entered failed state.
```

I just removed the symlink to knxd.socket by deleting the "file"
/etc/systemd/system/sockets.target.wants/knxd.socket

Now everything works fine, even after reboot. So maybe there is a problem with the 
Also=knxd.socket
in the service file?

**Comment by Foxi352** [comment] 2017-03-26 08:55
I confirm the same test error "Bad argument D" on standard x64 Debian GNU/Linux 8.7 (jessie). Latest master checkout of today.

**Comment by smurfix** [comment] 2017-03-26 09:03
@Foxi352 which git commit ID? 'Cause I uploaded a fix yesterday …

**Comment by Foxi352** [comment] 2017-03-26 09:08
serge@srvsmarthome:~/knxd$ git describe --tags
v0.14.4-16-g2e21350

serge@srvsmarthome:~/knxd$ git rev-parse HEAD
2e21350750b661d5843f96b33961c47bfd93460f

**Comment by smurfix** [comment] 2017-03-26 09:54
Ah. Sorry, my fault. Fix is actually in 8a93162 which was on a separate test computer. Uploaded.

**Comment by Foxi352** [comment] 2017-03-26 10:22
v0.14.4-25-gf8e87bb builds now without problems. Danke !

I will try installing over my existing v0.10.0 as soon as i have a bit more time because i will likely run into similar troubles than onkelandy... Maybe this evening.

**Comment by smurfix** [comment] 2017-03-26 12:28
There may still be problems with flow control. I plan to do some in-depth testing tonight.

**Comment by chefkoch009** [comment] 2017-03-26 15:08
Corresponding to the other thread "No Feedback from device after writing to actuator com-object #236" it seems that i don't get the ACK of package i sent to actuator via knxd. The Status i get.

**Comment by Foxi352** [comment] 2017-03-26 17:23
Ok, so I replaced my 0.10.0 with 0.14.5 just now.
I created /etc/knxd.ini with the following content:

```
[A.unix]
path = /tmp/eib
server = knxd_unix
systemd-ignore = false
[B.ipt]
driver = ipt
ip-address = 192.168.2.250
[C.pace]
delay = 30
filter = pace
[main]
addr = 0.0.1
client-addrs = 0.0.2:8
connections = A.unix,B.ipt
systemd = systemd
[systemd]
filters = C.pace
```

In /etc/knxd.conf i replaced the ARGS line with the following:
`KNXD_OPTS="/etc/knxd.ini"`

The result when starting "systemctl start knxd.socket" is the following in journalctl -xn:

```
-- Unit knxd.service has begun starting up.
Mar 26 19:15:41 srvsmarthome knxd[31132]: knxd: inifile.cpp:75: std::string& IniSection::operator[](const char*): Assertion `v != values.end()' failed.
Mar 26 19:15:41 srvsmarthome systemd[1]: knxd.service: main process exited, code=killed, status=6/ABRT
Mar 26 19:15:41 srvsmarthome systemd[1]: Failed to start KNX Daemon.
-- Subject: Unit knxd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit knxd.service has failed.
```
So it seems i run into the same issue than onkelandy.

**Comment by onkelandy** [comment] 2017-03-26 17:26
Did you try to remove the "" in knxd.conf?
Did you try to start it manually without the service?
Try to kill everything including knxd.socket and then also manually start the service (no autostart on reboot)

**Comment by Foxi352** [comment] 2017-03-26 17:37
What "" are you talking about ?

I only have 1 single line in knxd.conf that is not commented out, and that one is
`KNXD_OPTS="/etc/knxd.ini"`
That's what i read in the forum how it should be, am i wrong ?

I removed the --send-delay=30 for now as i had strange C.pace errors. So my actual knxd.ini is 

```
[A.unix]
path = /tmp/eib
server = knxd_unix
systemd-ignore = false
[B.ipt]
driver = ipt
ip-address = 192.168.2.250
[main]
addr = 0.0.1
client-addrs = 0.0.2:8
connections = A.unix,B.ipt
systemd = systemd
```

When i stop everything and then only start "journalctl start knxd.service" the service starts without problems. But the tcp socket :6720 is missing then.

When i start "journalctl start knxd.socket" the .socket starts without errors and then tries to start the .service which leads to the assertion error some posts above.

**Comment by onkelandy** [comment] 2017-03-26 17:41
Ich meinte die Anführungszeichen.. aber offenbar stört ihn das ja nicht ;)
Da du ja auch über IPT fährst, probier mal meine INI Konfiguration. Zumindest zum Testen. 

Töte knxd.socket und service und starte es dann über "knxd /etc/knxd.ini"

```
[A.tcp]
server = knxd_tcp
systemd-ignore = true
[B.ipt]
driver = ipt
filters = C.pace
ip-address = 192.168.2.250
[C.pace]
delay = 50
filter = pace
[main]
addr = 0.0.1
client-addrs=0.0.2:8
cache = D.cache
connections = A.tcp,B.ipt
systemd = systemd
background = true
```

**Comment by Foxi352** [comment] 2017-03-26 17:52
Das funktioniert soweit. Auch wenn ich "systemctl start knxd.service" alleine direkt starte ohne über den .socket zu fahren.

Aber eigentlich sollte der knxd.socket Dienst ja den knxd.service automatisch starten sobald jemand auf das Socket zugreift, oder habe ich das falsch verstanden ?

Auf jedenfall funktioniert es wenn ich das .socket stoppe und den .service mit deiner .ini starte. Danke dafür. Ich habe übrigends ein MDT IP Gateway, denke das ist ein Weinzierl OEM soweit ech das inzwischen mitgekriegt habe.

**Comment by onkelandy** [comment] 2017-03-26 18:08
Keine Ahnung.. ich kapier das mit dem socket ohnehin nicht ;)
Ich würde jedenfalls empfehlen, aus dem Service-File das Also=socket zu entfernen und dann systemctl enable knxd zu starten, um knxd bei jedem Systemstart sauber starten zu können.

Somit schließ ich mal den Issue hier.. Für alles weitere bräuchte es dann wohl einen neuen ;)

**Comment by smurfix** [comment] 2017-03-26 21:27
Das systemd-Startproblem ist behoben in v0.14.6

Das Also=socket zu entfernen ist keine gute Idee. Nur weil du das nicht kapierst heisst nicht dass es sinnfrei ist. :-P
Stichwort "socket activation".

**Comment by Foxi352** [comment] 2017-03-26 21:47
Ok, jetzt wird's schräg :-)

Also, ich kann dir erstmal bestätigen, dass das Startproblem jetzt gelöst ist. knxd.socket startet ohne Probleme und startet dann knxd.service. Smarthome verbindet sich auf tcp 6720 ohne Fehlermeldung. 

Allerdings besteht keine KNX Kommunikation. Das heisst Smarthome sendet weder noch empfängt es KNX Telegramme, zeigt mir aber eine korrekte Verbindung zu knxd an.

Wenn ich dann alles stoppe und nur knxd.service selbst starte (ohne knxd.socket vorher zu starten) funktioniert alles sofort.

Kann das an der knxd.ini liegen ? Ich hab die oben von onkelandy gepostete benutzt. Ich sehe da einen Unterschied, dass in meiner die ich per knxd_args erstellt hatte A.socket stand und in seiner A.tcp steht.

**Comment by smurfix** [comment] 2017-03-26 22:20
A.bla und B.fasel ist nur die Reihenfolge der Optionen, der knxd_args buchstabiert sie halt der Reihe nach durch, das hat nix zu sagen.

Schon möglich dass sich da noch ein Bug versteckt, ich teste das morgen nochmal gründlich durch.

**Comment by onkelandy** [comment] 2017-03-26 22:25
Es ging auch weniger um A oder B sondern um
[A.unix]
path = /tmp/eib
server = knxd_unix
systemd-ignore = false

oder
[A.tcp]
server = knxd_tcp
systemd-ignore = true

mit den entsprechenden Einträgen unter connections.
Ich habe nun beides mit der neueste Version getestet. Auch mal beides zusammen in connections eingetragen (zusätzlich zu ipt). Immer das gleiche Ergebnis:
knxd.service startet jetzt sauber, also kein Abbruch wegen ini-Fehler. Dafür keine Verbindung zum KNX (groupswrite bleibt einfach hängen)

Nach wie vor einzige Lösung, knxd.socket aus'm Startup zu entfernen. Ich mach den issue doch nochmals auf, auch wenn er mit dem ursprünglichen Prob nix mehr zu tun hat ;)

**Comment by smurfix** [comment] 2017-03-26 22:36
Dann sag mir mal (a) dein komplettes .ini, (b) was "lsof -i:6720 /var/run/knx /run/knx /tmp/eib" bei dir ausspuckt wenn du in dieser "groupswrite bleibt hängen"-Situation bist.

NB: immer erst .socket, dann .service stoppen oder starten.

**Comment by onkelandy** [comment] 2017-03-26 22:49
Komplettes ini ist gleich wie oben.. plus dem unix-Part testhalber.. also:
```
[A.tcp]
server = knxd_tcp
systemd-ignore = true
[A.unix]
path = /tmp/eib
server = knxd_unix
systemd-ignore = false
[B.ipt]
driver = ipt
filters = C.pace
ip-address = 10.0.0.101
[C.pace]
delay = 50
filter = pace
#ip-address = 10.0.0.101
[main]
addr = 1.1.65
client-addrs=1.1.66:8
cache = D.cache
connections = A.tcp,B.ipt
#alternativtest: connections = A.unix, B.ipt
#alternativtest: connections = A.tcp,A.unix,B.ipt
systemd = systemd
background = true
```

Befehle nach dem Stoppen von socket und service:
```
(#)~:$ systemctl start knxd.socket                                                                                                                                                                
(#)~:$ systemctl start knxd.service
(#)~:$ groupswrite ip:127.0.0.1 3/0/6 1                  
```

Output des lsof bei connections=A.tcp,B.ipt:
```
(#)~:$ lsof -i:6720 /var/run/knx /run/knx /tmp/eib                                                                                                                                                  00:40:58
lsof: status error on /tmp/eib: No such file or directory
COMMAND    PID  USER   FD   TYPE     DEVICE SIZE/OFF  NODE NAME
systemd      1  root   34u  unix 0xb51dea00      0t0 29075 /var/run/knx
systemd      1  root   35u  IPv6      29077      0t0   TCP *:6720 (LISTEN)
python3   1402 admin   21u  IPv4      30887      0t0   TCP localhost:37150->localhost:6720 (ESTABLISHED)
knxd      3382  knxd    3u  unix 0xb51dea00      0t0 29075 /var/run/knx
groupswri 3401  root    3u  IPv4      29152      0t0   TCP localhost:37158->localhost:6720 (ESTABLISHED)
```                                                                                                                                           
Output des lsof bei connections=A.unix,B.ipt:
```    
(#)~:$ lsof -i:6720 /var/run/knx /run/knx /tmp/eib                                                                                                                                                  00:40:59
COMMAND    PID  USER   FD   TYPE     DEVICE SIZE/OFF  NODE NAME
systemd      1  root   34u  unix 0xb1386400      0t0 33596 /var/run/knx
systemd      1  root   35u  IPv6      33598      0t0   TCP *:6720 (LISTEN)
python3   1402 admin   21u  IPv4      32509      0t0   TCP localhost:37186->localhost:6720 (ESTABLISHED)
knxd      3613  knxd    3u  unix 0xb1386400      0t0 33596 /var/run/knx
knxd      3613  knxd    6u  unix 0xb1218c00      0t0 32502 /tmp/eib
groupswri 3619  root    3u  IPv4      33650      0t0   TCP localhost:37188->localhost:6720 (ESTABLISHED)
```    

Wenn ich knxd.socket STOPPE, kommt folgender Output. groupswrite und smarthomeNG KNX Verbindung funktionieren problemlos, solange A.tcp im ini File drin ist.
```    
(#)~:$ lsof -i:6720 /var/run/knx /run/knx /tmp/eib
COMMAND  PID  USER   FD   TYPE     DEVICE SIZE/OFF  NODE NAME
python3 1402 admin   21u  IPv4      35658      0t0   TCP localhost:37230->localhost:6720 (ESTABLISHED)
knxd    3858  knxd    5u  unix 0xb1385b00      0t0 36722 /tmp/eib
knxd    3858  knxd    6u  IPv4      36723      0t0   TCP *:6720 (LISTEN)
knxd    3858  knxd    7u  IPv4      36731      0t0   TCP localhost:6720->localhost:37230 (ESTABLISHED)
```

**Comment by smurfix** [comment] 2017-03-27 06:23
Fixed (for real this time) in commit 7d0fdae

**Closed by smurfix** 2017-03-27 06:23 UTC

**Comment by onkelandy** [comment] 2017-03-27 06:45
confirmed. Seems to work now, thx.

**Comment by Foxi352** [comment] 2017-03-27 10:33
Confirmed also for x64. Thanks !
