### ISSUE TITLE
Cannot Communicate with KNX

### ISSUE THREAD

**Issue by berhankanbur** [knxd/knxd#536] opened 2022-05-20 14:41 UTC
I have an ABB USB/S.1.2 USB interface. I want to run KNXD but. I can't speak to KNX anyway.

In Tunneling, I get Link Down terminating error,
I am not getting any errors in routing but it is not sending or receiving data.

Here is the result I get when I run the ps ax|grep knxd command. ;
![Capture](https://user-images.githubusercontent.com/64873540/169551614-e932ae68-7f04-4543-871e-c1eb9b074a26.PNG)

I don't know much about Linux and knxd. I may be making a mistake because my English is also poor.

I have read almost most of the articles but I can't reach the conclusion. Please help me.

**Comment by dallmair** [comment] 2024-10-28 22:03
As this is happening with an ABB USB/S.1.2, the problem is most likely fixed with the merge of #570, i.e. in version 0.14.66.

@smurfix Please close. Thanks.

**Closed** 2024-10-29 02:54 UTC
